force-app/main/default/objects/CongaURL_Settings__c/CongaURL_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CongaURL_Settings</label>
</CustomObject>

force-app/main/default/objects/CongaURL_Settings__c/fields/AD__c.field-meta.xml
<CustomField>
    <fullName>AD__c</fullName>
    <label>AD</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CongaURL_Settings__c/fields/Comm_TempID__c.field-meta.xml
<CustomField>
    <fullName>Comm_TempID__c</fullName>
    <label>Comm TempID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CongaURL_Settings__c/fields/Days_Prior_to_Maturity_120__c.field-meta.xml
<CustomField>
    <fullName>Days_Prior_to_Maturity_120__c</fullName>
    <label>Days Prior to Maturity 120</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CongaURL_Settings__c/fields/Days_Prior_to_Maturity_60__c.field-meta.xml
<CustomField>
    <fullName>Days_Prior_to_Maturity_60__c</fullName>
    <label>Days Prior to Maturity 60</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CongaURL_Settings__c/fields/DueDetailsLines__c.field-meta.xml
<CustomField>
    <fullName>DueDetailsLines__c</fullName>
    <label>DueDetailsLines</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CongaURL_Settings__c/fields/Equipment_contact__c.field-meta.xml
<CustomField>
    <fullName>Equipment_contact__c</fullName>
    <label>Equipment contact</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CongaURL_Settings__c/fields/FinanceFee__c.field-meta.xml
<CustomField>
    <fullName>FinanceFee__c</fullName>
    <label>FinanceFee</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CongaURL_Settings__c/fields/INSFEE__c.field-meta.xml
<CustomField>
    <fullName>INSFEE__c</fullName>
    <label>INSFEE</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CongaURL_Settings__c/fields/InterimRent__c.field-meta.xml
<CustomField>
    <fullName>InterimRent__c</fullName>
    <label>InterimRent</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CongaURL_Settings__c/fields/INV__c.field-meta.xml
<CustomField>
    <fullName>INV__c</fullName>
    <label>INV</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CongaURL_Settings__c/fields/InvoiceEverGreenTempID__c.field-meta.xml
<CustomField>
    <fullName>InvoiceEverGreenTempID__c</fullName>
    <label>InvoiceEverGreenTempID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CongaURL_Settings__c/fields/LateFee__c.field-meta.xml
<CustomField>
    <fullName>LateFee__c</fullName>
    <label>LateFee</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CongaURL_Settings__c/fields/MutipleStatesCommTempID__c.field-meta.xml
<CustomField>
    <fullName>MutipleStatesCommTempID__c</fullName>
    <label>MutipleStatesCommTempID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CongaURL_Settings__c/fields/OrigFee__c.field-meta.xml
<CustomField>
    <fullName>OrigFee__c</fullName>
    <label>OrigFee</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CongaURL_Settings__c/fields/Specific_RI_TempID__c.field-meta.xml
<CustomField>
    <fullName>Specific_RI_TempID__c</fullName>
    <label>Specific RI TempID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CongaURL_Settings__c/fields/States_Prior_to_Maturity_120__c.field-meta.xml
<CustomField>
    <fullName>States_Prior_to_Maturity_120__c</fullName>
    <label>States Prior to Maturity 120</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CongaURL_Settings__c/fields/States_Prior_to_Maturity_RI_120__c.field-meta.xml
<CustomField>
    <fullName>States_Prior_to_Maturity_RI_120__c</fullName>
    <label>States Prior to Maturity RI 120</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>This object is used to capture the consolidation of Bills and Charges</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000000000}</displayFormat>
        <label>Invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/LS_Contract__c.field-meta.xml
<CustomField>
    <fullName>LS_Contract__c</fullName>
    <label>LS Contract</label>
    <referenceTo>cllease__Lease_Account__c</referenceTo>
    <relationshipLabel>Invoice</relationshipLabel>
    <relationshipName>Invoice</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CongaGenerateInvoice.cls
Global Class CongaGenerateInvoice{
   
 static String version = DLLNewCoConstants.SOAP_VERSION;
 static String partnerUrl = Url.getSalesforceBaseUrl().toExternalForm()+version+UserInfo.getOrganizationId().subString(0,15);  
 static String congaUrl;
 static string InvTempId;
 static integer countSpecificStates;
 static integer countOfRIstate;
 static integer countOfOtherStates;
 
   // this  method is used to generate Credit Approval Document
  Webservice static string generateInvoiceDocument(string recordId){
    
      string BillId       = '';
      string contId       = '';
      countSpecificStates = 0;
      countOfRIstate      = 0;
      countOfOtherStates  = 0;
      String StateCodes      = CongaURL_Settings__c.getInstance().States_Prior_to_Maturity_120__c;
      String RIStateCode     = CongaURL_Settings__c.getInstance().States_Prior_to_Maturity_RI_120__c;
      Decimal Days120        = CongaURL_Settings__c.getInstance().Days_Prior_to_Maturity_120__c;
      Decimal Days60         = CongaURL_Settings__c.getInstance().Days_Prior_to_Maturity_60__c;
      List<String> Oth = new List<String>();
      List<String> Ri = new List<String>();
        for(String st : StateCodes.split(','))
        {
           if(st !=null)
           {
               Oth.add(st);
           }
           System.debug('***oth-list****'+Oth);
        }
        
        for(String stRI     : RIStateCode.split(','))
        {
           if(stRI !=null)
           {
               Ri.add(stRI);
           }
           System.debug('***Ri-list****'+Ri);
        }
      list<Invoice__c> inv =  [select id, name,LS_Contract__r.id,LS_Contract__r.Number_of_Days_TO_Mature__c,LS_Contract__r.cllease__Lease_Status__c,LS_Contract__r.Billing_Address__r.state__c,LS_Contract__r.State__c,(select id, name from Invoice_Bills__r) 
                              from Invoice__c where id =:recordId limit 1];
      if(inv.size()>0)
      {
         
      
      if(inv[0].Invoice_Bills__r.size()>0)
      {
          BillId = inv[0].Invoice_Bills__r[0].Id;
          contId = inv[0].LS_Contract__r.id;
          System.debug('Bill ID'+BillId);
          System.debug('LS Contract ID'+contId);
        //Quering all the Child records of particular Contract with Contract id  
        List<cllease__Contract_Equipment__c> ContractEquipmentList = [Select id,name,State__c,cllease__Contract__r.id,cllease__Contract__r.cllease__Lease_Status__c,cllease__Contract__r.Number_of_Days_TO_Mature__c 
                                                                      From cllease__Contract_Equipment__c Where cllease__Contract__r.id =: inv[0].LS_Contract__r.id 
                                                                       AND cllease__Contract__r.Number_of_Days_TO_Mature__c <=: Days120 
                                                                       AND cllease__Contract__r.cllease__Lease_Status__c != 'EVERGREEN'];
                                                                       
        System.debug('*********ContractEquipmentList*********'+ContractEquipmentList.size());
        //Chage for EOL-002 ticket
        //Here we are Getting the Count of Equipment as per State
        if(ContractEquipmentList.size()>0)
        {
            for(cllease__Contract_Equipment__c CE : ContractEquipmentList)
            {
                if(Oth.contains(CE.state__c) && CE.cllease__Contract__r.Number_of_Days_TO_Mature__c <= Days120)
                {
                    countSpecificStates++;
                }
                if(Ri.contains(CE.State__c) && CE.cllease__Contract__r.Number_of_Days_TO_Mature__c <= Days120)
                {
                    countOfRIstate++;
                }
                if(!Ri.contains(CE.State__c) && !Oth.contains(CE.State__c) && CE.cllease__Contract__r.Number_of_Days_TO_Mature__c <= Days60)
                {
                    countOfOtherStates++;
                }
                    
            }
        }           
        String DueDetailsLines = CongaURL_Settings__c.getInstance().DueDetailsLines__c;
        String FinanceFee      = CongaURL_Settings__c.getInstance().FinanceFee__c;
        String INSFEE          = CongaURL_Settings__c.getInstance().INSFEE__c;
        String InterimRent     = CongaURL_Settings__c.getInstance().InterimRent__c;
        String Invo            = CongaURL_Settings__c.getInstance().INV__c;
        String LateFee         = CongaURL_Settings__c.getInstance().LateFee__c;
        String OrigFee         = CongaURL_Settings__c.getInstance().OrigFee__c;
        String AD              = CongaURL_Settings__c.getInstance().AD__c;
        String Equipment       = CongaURL_Settings__c.getInstance().Equipment_contact__c;
        
        
            //Change for EOL=002 Ticket
            //Based on the Count of States we assigning the template id 
            if(inv[0].LS_Contract__r.cllease__Lease_Status__c != 'EVERGREEN')
            {
             
               if(countOfRIstate > 0 && (countSpecificStates > 0 || countOfOtherStates > 0)){

                   InvTempId       = CongaURL_Settings__c.getInstance().MutipleStatesCommTempID__c;
               }
               else if(countOfRIstate > 0 && countSpecificStates == 0 && countOfOtherStates == 0){
                   
                   InvTempId       = CongaURL_Settings__c.getInstance().Specific_RI_TempID__c;   
               }
               else if(countOfRIstate == 0 && (countSpecificStates > 0 || countOfOtherStates > 0)){
                   
                   InvTempId       = CongaURL_Settings__c.getInstance().Comm_TempID__c;
               }
               else if(countOfRIstate == 0 &&  countSpecificStates == 0 && countOfOtherStates == 0){
                   
                   InvTempId     = CongaURL_Settings__c.getInstance().InvoiceEverGreenTempID__c; 
               }
            }           
            else
            {
                InvTempId       = CongaURL_Settings__c.getInstance().InvoiceEverGreenTempID__c;
                System.debug('*****i entered into the other states  else block*******');
            }
     System.debug('*****InvTempId****'+invTempId);
     congaUrl =Label.Conga_URL+userinfo.getsessionId()+'&serverUrl='+partnerUrl+'&QueryId=[INV]'+Invo+',[DueDetailsLines]'
              +DueDetailsLines+'?pv0='+BillId+',[AD]'+AD+'?pv0='+contId+',[INSFEE]'+INSFEE+'?pv0='+recordId+',[OrigFee]'
              +OrigFee+'?pv0='+recordId+',[InterimRent]'+InterimRent+'?pv0='+recordId+',[LateFee]'+LateFee+'?pv0='
              +recordId+',[FinanceFee]'+FinanceFee+',[EC]'+Equipment+'?pv0='+contId+'&TemplateId='
              +InvTempId+'&DS7=1&OFN=InvoiceStatement&id='+recordId.subString(0,15);
      return getCalloutToConga(congaUrl);
      }
      else{
       return 'There is no bill for this invoice';

      }
    }
    else
        return  null;
    }
    
    public static String getCalloutToConga(String url) {

    // Instantiate a new http object
    Http h = new Http();

    // Instantiate a new HTTP request, specify the method (GET) as well as the endpoint
    HttpRequest req = new HttpRequest();
    req.setEndpoint(url);
    req.setMethod('GET');
    req.setTimeout(60000);
    // Send the request, and return a response
    HttpResponse res = h.send(req);
     if(res.getStatusCode() != 200){
                return res.getStatus();
     }else if(!Pattern.matches('[a-zA-Z0-9]{18}',res.getBody())){
                return res.getBody();
      }
     return 'Document generated successfully'; 
    }  
    
      }