force-app/main/default/objects/Dealers_and_Users__c/Dealers_and_Users__c.object-meta.xml
<CustomObject>
    <description>junction object between Dealers and Users related to them</description>
    <label>Dealers and Users</label>
    <nameField>
        <displayFormat>DU-{0000}</displayFormat>
        <label>Dealer and Users Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealers and Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealers_and_Users__c/fields/Admin_User__c.field-meta.xml
<CustomField>
    <fullName>Admin_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Admin User</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Only Users with Dealer User role can be linked to a Dealer</errorMessage>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Dealer User</value>
        </filterItems>
        <infoMessage>Only Users with Dealer User role can be linked to a Dealer</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Dealers_and_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dealers_and_Users__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <label>Dealer</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account record type must be Dealer</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Dealer</value>
        </filterItems>
        <infoMessage>Accounts with record type Dealer</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Admin Users</relationshipLabel>
    <relationshipName>Dealers_and_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PopulateDealer.cls
/*
Author: CLS
Summary: Class to populate the dealer related to logged-in user when new Credit approval record is created.
*/

global class PopulateDealer{

    /*
    
    SNEHA :: This class is no more used. defaulting dealer account is handled on skuid page. 16th March, 2018



    webservice static Account func_popdeal(){
    
        Dealers_and_Users__c[] du = [Select id,
                                            Admin_User__c,
                                            Dealer__c,
                                            Primary__c 
                                            from Dealers_and_Users__c 
                                            where Admin_User__c = :UserInfo.getUserId() 
                                                and Primary__c = true];
    
        Account acc = [select id, name from Account where id = :du[0].Dealer__c];
    
        if(du.size() == 1){
            return acc;
        }
        else
            return new Account();

    }
    */
}