force-app/main/default/objects/Int_Batch_Status__c/Int_Batch_Status__c.object-meta.xml
<CustomObject>
    <label>Int Batch Status</label>
    <nameField>
        <label>Int Batch Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Int Batch Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Batch_Status__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_PX_Remit__c/Int_PX_Remit__c.object-meta.xml
<CustomObject>
    <description>This contains payments received from PNC</description>
    <label>Int PX Remit</label>
    <nameField>
        <displayFormat>RE-{00000000}</displayFormat>
        <label>Int PX Remint Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int PX Remit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_PX_Remit__c/fields/Account_Num__c.field-meta.xml
<CustomField>
    <fullName>Account_Num__c</fullName>
    <label>Account Num</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_PX_Remit__c/fields/Check__c.field-meta.xml
<CustomField>
    <fullName>Check__c</fullName>
    <label>Check</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_PX_Remit__c/fields/Committed__c.field-meta.xml
<CustomField>
    <fullName>Committed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Committed?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Int_PX_Remit__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Int PX Remit</relationshipLabel>
    <relationshipName>Int_PX_Remit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Int_PX_Remit__c/fields/Invoice_Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Amount_Paid__c</fullName>
    <label>Invoice Amount Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Int_PX_Remit__c/fields/Payment_Batch_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Batch_Date__c</fullName>
    <label>Payment Batch Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Int_PX_Remit__c/fields/Payment_Batch_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Batch_Total_Amount__c</fullName>
    <label>Payment Batch Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Int_PX_Remit__c/fields/Record_Number__c.field-meta.xml
<CustomField>
    <fullName>Record_Number__c</fullName>
    <label>Record Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_PX_Remit__c/fields/Remark__c.field-meta.xml
<CustomField>
    <fullName>Remark__c</fullName>
    <description>This field track Status about Creating Payments processing .</description>
    <inlineHelpText>This field track Status about Creating Payments processing .</inlineHelpText>
    <label>Remark</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_PX_Remit__c/fields/Trans_Source__c.field-meta.xml
<CustomField>
    <fullName>Trans_Source__c</fullName>
    <label>Trans Source</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_PX_Remit__c/fields/Trans_UID__c.field-meta.xml
<CustomField>
    <fullName>Trans_UID__c</fullName>
    <label>Trans UID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_PX_Remit__c/fields/Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Amount__c</fullName>
    <label>Transaction Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Int_PX_Remit__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>This object is used to capture the consolidation of Bills and Charges</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000000000}</displayFormat>
        <label>Invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Balance_Due_Amount__c.field-meta.xml
<CustomField>
    <fullName>Balance_Due_Amount__c</fullName>
    <formula>Total_Invoiced_Amount__c - Paid_Invoice_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance Due Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/LS_Contract__c.field-meta.xml
<CustomField>
    <fullName>LS_Contract__c</fullName>
    <label>LS Contract</label>
    <referenceTo>cllease__Lease_Account__c</referenceTo>
    <relationshipLabel>Invoice</relationshipLabel>
    <relationshipName>Invoice</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AP_ManualPayment.cls
global with sharing class AP_ManualPayment {

    public Static boolean manualPayment = false;

    @AuraEnabled
	public static String addPayment(String recordId, String checkNumber, Decimal checkAmount, Date paymentDate){
		
        Map<String,String> response = new Map<String,String>();

        /* grab the account number */
        Invoice__c i = [SELECT name, balance_due_amount__c, LS_Contract__r.cllease__Account__r.account_number__c
                      FROM Invoice__c
                      where id = :recordId
                      ];

        List<Int_PX_Remit__c> paymentsPending = new List<Int_PX_Remit__c>();

        paymentsPending = [select id 
                            from Int_PX_Remit__c 
                            where Invoice_number__c = :i.name
                            ];

        if (paymentsPending.size() > 0){
             response.put('Message','There is already a payment pending for this invoice!');
            return JSON.serialize(response);
        }

        if (i.balance_due_amount__c < checkAmount){
            response.put('Message','Check amount must be less than or equal to the balance due!');
            return JSON.serialize(response);
        }
            

        Int_PX_Remit__c r = new Int_PX_Remit__c();
 
        r.account_num__c = i.LS_Contract__r.cllease__Account__r.account_number__c;
        r.check__c = 'CHK' + checkNumber;
        r.committed__c = false;
        r.date__c = paymentDate;
        r.invoice__c = recordId;
        r.invoice_number__c = i.name;
        r.invoice_amount_paid__c = checkAmount;
        r.invoice_amount__c = checkAmount;
        r.payment_batch_date__c = paymentDate;
        r.payment_Batch_total_amount__c = checkAmount;
        r.record_number__c = 1;
        r.transaction_amount__c = checkAmount;
        r.transaction_type__C = checkNumber;
        r.trans_source__c = 'PX';
        r.remark__c = 'Manual Payment Recorded';
        r.trans_UID__c = string.valueOf(paymentDate.year()) + string.valueOf(paymentDate.month()) + string.valueOf(paymentDate.day());

        manualPayment = true;

        insert r;

        Int_Batch_Status__c b = new Int_Batch_Status__c();
        b.status__c = 'Ready';
        b.Name = 'PX Remit';
        insert b;

        PNCUtility.voidInvoice(recordId,false);
        
        return JSON.serialize(response);


	}

}