force-app/main/default/objects/ICS_Application__c/ICS_Application__c.object-meta.xml
<CustomObject>
    <description>This links to a quick quote and provides the data related to credit request</description>
    <label>ICS Application Request</label>
    <nameField>
        <displayFormat>ICS-{00000000}</displayFormat>
        <label>ICS Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ICS_Application__c/fields/Quick_Quote__c.field-meta.xml
<CustomField>
    <fullName>Quick_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quick Quote</label>
    <referenceTo>genesis__Quick_Quotes__c</referenceTo>
    <relationshipName>ICSResponses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ICS_Application__c/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <label>Transaction Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ICVAsyncICSCredit.cls
/*******************************************************************************************************************
*   ICVAsyncICSCredit
* 
*	Change Log: 
*	11/12/18 - MRM Created
* 
********************************************************************************************************************/
public class ICVAsyncICSCredit implements Queueable, Database.AllowsCallouts {
    
    private String myISODateTime = string.valueOf(json.serialize(datetime.now()));
    private String applicationId;
    private String messageId;
    public  ICVAsyncICSCredit(String applicationId, String messageId)
    {
        this.applicationId = applicationId;
        this.messageId = messageId;
    }
    
    public void execute(QueueableContext context) {
    	ICS_Application__c ar = [select quick_quote__c 
    									,transaction_id__c
    									from ICS_Application__c
    									where id = :applicationId ]; 
    									
    	Map<ID,String> quickQuoteMap = new Map<ID,String>(); 
		quickQuoteMap.put(ar.quick_quote__c,'Hello');
		//ICSUtility.sendRequest(quickQuoteMap,false,false,messageId,ar.transaction_id__c);
		if (ICSUtility.sendRequest(quickQuoteMap,false,false,messageId,ar.transaction_id__c)){ 
    		system.debug('Called getICS Credit ' + system.now());
    		ICVAsyncGetCommitmentLE job = new ICVAsyncGetCommitmentLE(applicationId);
        	System.enqueueJob(job);
		} 
    }
    
}