force-app/main/default/objects/ICS_Application__c/ICS_Application__c.object-meta.xml
<CustomObject>
    <description>This links to a quick quote and provides the data related to credit request</description>
    <label>ICS Application Request</label>
    <nameField>
        <displayFormat>ICS-{00000000}</displayFormat>
        <label>ICS Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ICS_Application__c/fields/Quick_Quote__c.field-meta.xml
<CustomField>
    <fullName>Quick_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quick Quote</label>
    <referenceTo>genesis__Quick_Quotes__c</referenceTo>
    <relationshipName>ICSResponses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ICVAsyncAddCreditCommitment.cls
/*******************************************************************************************************************
*   ICVAsyncAddCreditCommitment
* 
*	Change Log: 
*	11/12/18 - MRM Created
* 
********************************************************************************************************************/
public class ICVAsyncAddCreditCommitment implements Queueable, Database.AllowsCallouts {
    
    private String myISODateTime = string.valueOf(json.serialize(datetime.now()));
    private String applicationId;
    private String messageId;
    private String action;
    
    public  ICVAsyncAddCreditCommitment(String applicationId, String messageId, String action)
    {
        this.applicationId = applicationId;
        this.messageId = messageId;
        this.action = action;
    }
    
    public void execute(QueueableContext context) {
    	 
    	ICS_Application__c ar = [select id
    				,quick_quote__r.name
	  				from ICS_Application__c
	  				where id = :applicationId 
	  				];
    	
    	boolean resultsOK = true;
    	
    	if (action == 'Score'){
    		map<String,String> requestInfoMap = new Map<String,String>();
			requestInfoMap.put('TransactionID',ICVUtility.getMessageId());
			requestInfoMap.put('SourceCommitmentID',ar.quick_quote__r.name);//q.name);
			requestInfoMap.put('SourceCommitmentType','A');
			resultsOK = ICVUtility.addCommitment(requestInfoMap,applicationId,'PEND');
	    	system.debug('Results OK are: ' + resultsOK);
    	}
    	
    	if (resultsOK && !Test.isRunningTest()){
    		system.debug('Execute Add Commitment Performed for ' + system.now());
    		ICVAsyncICSCredit job = new ICVAsyncICSCredit(applicationId,messageId);
        	System.enqueueJob(job); 
    	} 
    		   
    } 
    
}