force-app/main/default/objects/FMZ_Welcome_Message__c/FMZ_Welcome_Message__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>FMZ Welcome Message</label>
</CustomObject>

force-app/main/default/objects/FMZ_Welcome_Message__c/fields/Background_Color_Hex_Code__c.field-meta.xml
<CustomField>
    <fullName>Background_Color_Hex_Code__c</fullName>
    <label>Background Color Hex Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FMZ_Welcome_Message__c/fields/Subtitle__c.field-meta.xml
<CustomField>
    <fullName>Subtitle__c</fullName>
    <description>Use &#39;{0}&#39; for current users name. Use &#39;{1}&#39; for the current users first name.</description>
    <inlineHelpText>Use &#39;{0}&#39; for current users name. Use &#39;{1}&#39; for the current users first name.</inlineHelpText>
    <label>Subtitle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FMZ_Welcome_Message__c/fields/Text_Color_Hex_Code__c.field-meta.xml
<CustomField>
    <fullName>Text_Color_Hex_Code__c</fullName>
    <label>Text Color Hex Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FMZ_Welcome_Message__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Use &#39;{0}&#39; for current users name. Use &#39;{1}&#39; for the current users first name.</description>
    <inlineHelpText>Use &#39;{0}&#39; for current users name. Use &#39;{1}&#39; for the current users first name.</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FMZ_WelcomeMessageControllerTest.cls
/**
 * Created by samuelmeyers on 12/11/18.
 */
@isTest
public class FMZ_WelcomeMessageControllerTest {
    @isTest
    public static void getWelcomeMessage(){
        FMZ_Welcome_Message__c message = FMZ_Welcome_Message__c.getOrgDefaults();
        message.Text_Color_Hex_Code__c = '000000';
        message.Background_Color_Hex_Code__c = '999999';
        message.Title__c = 'TEST TITLE';
        message.Subtitle__c = 'TEST SUBTITLE';
        insert message;

        FMZ_WelcomeMessageController.MessageSetting setting = FMZ_WelcomeMessageController.getWelcomeMessage();

        System.assert(setting != null);
    }
}