force-app/main/default/objects/FMZ_Welcome_Message__c/FMZ_Welcome_Message__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>FMZ Welcome Message</label>
</CustomObject>

force-app/main/default/objects/FMZ_Welcome_Message__c/fields/Background_Color_Hex_Code__c.field-meta.xml
<CustomField>
    <fullName>Background_Color_Hex_Code__c</fullName>
    <label>Background Color Hex Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FMZ_Welcome_Message__c/fields/Subtitle__c.field-meta.xml
<CustomField>
    <fullName>Subtitle__c</fullName>
    <description>Use &#39;{0}&#39; for current users name. Use &#39;{1}&#39; for the current users first name.</description>
    <inlineHelpText>Use &#39;{0}&#39; for current users name. Use &#39;{1}&#39; for the current users first name.</inlineHelpText>
    <label>Subtitle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FMZ_Welcome_Message__c/fields/Text_Color_Hex_Code__c.field-meta.xml
<CustomField>
    <fullName>Text_Color_Hex_Code__c</fullName>
    <label>Text Color Hex Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FMZ_Welcome_Message__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Use &#39;{0}&#39; for current users name. Use &#39;{1}&#39; for the current users first name.</description>
    <inlineHelpText>Use &#39;{0}&#39; for current users name. Use &#39;{1}&#39; for the current users first name.</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FMZ_WelcomeMessageController.cls
/**
 * Created by samuelmeyers on 12/11/18.
 */

public without sharing class FMZ_WelcomeMessageController {
    @AuraEnabled
    public static MessageSetting getWelcomeMessage(){
        FMZ_Welcome_Message__c setting = FMZ_Welcome_Message__c.getOrgDefaults();

        return new MessageSetting(
                setting.Text_Color_Hex_Code__c,
                setting.Background_Color_Hex_Code__c,
                setting.Title__c.replaceAll('\\{0\\}', UserInfo.getName()).replaceAll('\\{1\\}', UserInfo.getFirstName()),
                setting.Subtitle__c.replaceAll('\\{0\\}', UserInfo.getName()).replaceAll('\\{1\\}', UserInfo.getFirstName())
        );
    }

    public class MessageSetting {
        @AuraEnabled
        public String textColor;

        @AuraEnabled
        public String backgroundColor;

        @AuraEnabled
        public String title;

        @AuraEnabled
        public String subtitle;

        public MessageSetting(String textColor, String backgroundColor, String title, String subtitle){
            this.textColor = textColor;
            this.backgroundColor = backgroundColor;
            this.title = title;
            this.subtitle = subtitle;
        }
    }
}