force-app/main/default/objects/Lease_Exposure__c/Lease_Exposure__c.object-meta.xml
<CustomObject>
    <label>Lease Exposure</label>
    <nameField>
        <label>Lease Exposure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lease Exposure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lease_Exposure__c/fields/Asset_Sale__c.field-meta.xml
<CustomField>
    <fullName>Asset_Sale__c</fullName>
    <label>Asset Sale</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lease_Exposure__c/fields/Evergreen_Billed__c.field-meta.xml
<CustomField>
    <fullName>Evergreen_Billed__c</fullName>
    <label>Evergreen Billed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lease_Exposure__c/fields/Evergreen_Billed_Not_Paid__c.field-meta.xml
<CustomField>
    <fullName>Evergreen_Billed_Not_Paid__c</fullName>
    <label>Evergreen Billed - Not Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lease_Exposure__c/fields/Exposure__c.field-meta.xml
<CustomField>
    <fullName>Exposure__c</fullName>
    <label>Exposure</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lease_Exposure__c/fields/Finance_Fees__c.field-meta.xml
<CustomField>
    <fullName>Finance_Fees__c</fullName>
    <label>Finance Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lease_Exposure__c/fields/Insurance_Fees__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Fees__c</fullName>
    <label>Insurance Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lease_Exposure__c/fields/Late_Fees__c.field-meta.xml
<CustomField>
    <fullName>Late_Fees__c</fullName>
    <label>Late Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lease_Exposure__c/fields/LS_Contract__c.field-meta.xml
<CustomField>
    <fullName>LS_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LS Contract</label>
    <referenceTo>cllease__Lease_Account__c</referenceTo>
    <relationshipLabel>Lease Exposure</relationshipLabel>
    <relationshipName>Lease_Exposure</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lease_Exposure__c/fields/NSF_Fees__c.field-meta.xml
<CustomField>
    <fullName>NSF_Fees__c</fullName>
    <label>NSF Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lease_Exposure__c/fields/Origination_Fees__c.field-meta.xml
<CustomField>
    <fullName>Origination_Fees__c</fullName>
    <label>Origination Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lease_Exposure__c/fields/Rent__c.field-meta.xml
<CustomField>
    <fullName>Rent__c</fullName>
    <inlineHelpText>Total of all rent</inlineHelpText>
    <label>Rent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lease_Exposure__c/fields/Rent_Accrual__c.field-meta.xml
<CustomField>
    <fullName>Rent_Accrual__c</fullName>
    <label>Rent Accrual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lease_Exposure__c/fields/Rent_Billed__c.field-meta.xml
<CustomField>
    <fullName>Rent_Billed__c</fullName>
    <label>Rent Billed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lease_Exposure__c/fields/Rent_Billed_Not_Paid__c.field-meta.xml
<CustomField>
    <fullName>Rent_Billed_Not_Paid__c</fullName>
    <label>Rent Billed - Not Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lease_Exposure__c/fields/Service_Fees__c.field-meta.xml
<CustomField>
    <fullName>Service_Fees__c</fullName>
    <label>Service Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lease_Exposure__c/fields/Termination_Quote_Fees__c.field-meta.xml
<CustomField>
    <fullName>Termination_Quote_Fees__c</fullName>
    <label>Termination Quote Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lease_Exposure__c/fields/Unearned_Income__c.field-meta.xml
<CustomField>
    <fullName>Unearned_Income__c</fullName>
    <label>Unearned Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lease_Exposure__c/fields/Unearned_Residual__c.field-meta.xml
<CustomField>
    <fullName>Unearned_Residual__c</fullName>
    <label>Unearned Residual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/EXExposureController.cls
/********************************************************************************************
*
*  Change Log:
*
*	02/28/19- MRM Created class for exposure viewing; cls is still classic so this is it
*
*********************************************************************************************/
public with sharing class EXExposureController{
    
    Lease_Exposure__c e;
    cllease__Lease_Account__c l;
    
    
    public EXExposurecontroller(ApexPages.StandardController stdController){
    	
    	this.l = (cllease__Lease_Account__c)stdController.getRecord();
    	     
    	l = [Select id from cllease__Lease_Account__c where id = :l.id];
  	} 

    /******************************************************************************************
    * Show Exposure
    *******************************************************************************************/
    public pageReference showExposure(){
        
        Set<String> leaseSet = new Set<String>();
        leaseSet.add(l.id);
        ExposureUtility.getExposure(leaseSet);

        e = [ SELECT Asset_Sale__c
                  ,Estimated_Property_Tax__c
                  ,Evergreen_Billed_Not_Paid__c
                  ,Evergreen_Billed__c
                  ,Exposure__c
                  ,Finance_Fees__c
                  ,Id,Insurance_Fees__c
                  ,Late_Fees__c
                  ,LS_Contract__c
                  ,Name
                  ,NSF_Fees__c
                  ,Origination_Fees__c
                  ,Rent_Accrual__c
                  ,Rent_Billed_Not_Paid__c
                  ,Rent_Billed__c
                  ,Rent__c
                  ,Residual_Amount__c
                  ,Service_Fees__c
                  ,Termination_Quote_Fees__c
                  ,Unearned_Income__c
                  ,Unearned_Residual__c 
                  FROM Lease_Exposure__c
                  where ls_contract__c = :l.id
            ];
        
        PageReference newPage = new PageReference('/' + e.id);
    	newPage.setRedirect(true);
		return newPage; 
    }
}