force-app/main/default/objects/FMZ_CTA_Settings__c/FMZ_CTA_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>FMZ CTA Settings</label>
</CustomObject>

force-app/main/default/objects/FMZ_CTA_Settings__c/fields/Complete_Apps_Action_Label__c.field-meta.xml
<CustomField>
    <fullName>Complete_Apps_Action_Label__c</fullName>
    <label>Complete Apps Action Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FMZ_CTA_Settings__c/fields/Complete_Apps_Call_to_Action__c.field-meta.xml
<CustomField>
    <fullName>Complete_Apps_Call_to_Action__c</fullName>
    <label>Complete Apps Call to Action</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FMZ_CTA_Settings__c/fields/Complete_Apps_Complete_Message__c.field-meta.xml
<CustomField>
    <fullName>Complete_Apps_Complete_Message__c</fullName>
    <label>Complete Apps Complete Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FMZ_CTA_Settings__c/fields/Complete_Apps_Image__c.field-meta.xml
<CustomField>
    <fullName>Complete_Apps_Image__c</fullName>
    <label>Complete Apps Image</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FMZ_CTA_Settings__c/fields/Complete_Apps_Info_Column_Label__c.field-meta.xml
<CustomField>
    <fullName>Complete_Apps_Info_Column_Label__c</fullName>
    <label>Complete Apps Info Column Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FMZ_CTA_Settings__c/fields/Complete_Apps_Label__c.field-meta.xml
<CustomField>
    <fullName>Complete_Apps_Label__c</fullName>
    <label>Complete Apps Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FMZ_CTA_Settings__c/fields/Complete_Apps_Name_Column_Label__c.field-meta.xml
<CustomField>
    <fullName>Complete_Apps_Name_Column_Label__c</fullName>
    <label>Complete Apps Name Column Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FMZ_CTA_Settings__c/fields/Convert_CC_Action_Label__c.field-meta.xml
<CustomField>
    <fullName>Convert_CC_Action_Label__c</fullName>
    <label>Convert CC Action Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FMZ_CTA_Settings__c/fields/Convert_CC_Call_to_Action__c.field-meta.xml
<CustomField>
    <fullName>Convert_CC_Call_to_Action__c</fullName>
    <label>Convert CC Call to Action</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FMZ_CTA_Settings__c/fields/Convert_CC_Complete_Message__c.field-meta.xml
<CustomField>
    <fullName>Convert_CC_Complete_Message__c</fullName>
    <label>Convert CC Complete Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FMZ_CTA_Settings__c/fields/Convert_CC_Image__c.field-meta.xml
<CustomField>
    <fullName>Convert_CC_Image__c</fullName>
    <label>Convert CC Image</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FMZ_CTA_Settings__c/fields/Convert_CC_Info_Column_Label__c.field-meta.xml
<CustomField>
    <fullName>Convert_CC_Info_Column_Label__c</fullName>
    <label>Convert CC Info Column Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FMZ_CTA_Settings__c/fields/Convert_CC_Label__c.field-meta.xml
<CustomField>
    <fullName>Convert_CC_Label__c</fullName>
    <label>Convert CC Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FMZ_CTA_Settings__c/fields/Convert_CC_Name_Column_label__c.field-meta.xml
<CustomField>
    <fullName>Convert_CC_Name_Column_label__c</fullName>
    <label>Convert CC Name Column label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FMZ_CTA_Settings__c/fields/Fund_Apps_Action_Label__c.field-meta.xml
<CustomField>
    <fullName>Fund_Apps_Action_Label__c</fullName>
    <label>Fund Apps Action Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FMZ_CTA_Settings__c/fields/Fund_Apps_Call_to_Action__c.field-meta.xml
<CustomField>
    <fullName>Fund_Apps_Call_to_Action__c</fullName>
    <label>Fund Apps Call to Action</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FMZ_CTA_Settings__c/fields/Fund_Apps_Complete_Message__c.field-meta.xml
<CustomField>
    <fullName>Fund_Apps_Complete_Message__c</fullName>
    <label>Fund Apps Complete Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FMZ_CTA_Settings__c/fields/Fund_Apps_Image__c.field-meta.xml
<CustomField>
    <fullName>Fund_Apps_Image__c</fullName>
    <label>Fund Apps Image</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FMZ_CTA_Settings__c/fields/Fund_Apps_Info_Column_Label__c.field-meta.xml
<CustomField>
    <fullName>Fund_Apps_Info_Column_Label__c</fullName>
    <label>Fund Apps Info Column Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FMZ_CTA_Settings__c/fields/Fund_Apps_Label__c.field-meta.xml
<CustomField>
    <fullName>Fund_Apps_Label__c</fullName>
    <label>Fund Apps Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FMZ_CTA_Settings__c/fields/Fund_Apps_Name_Column_Label__c.field-meta.xml
<CustomField>
    <fullName>Fund_Apps_Name_Column_Label__c</fullName>
    <label>Fund Apps Name Column Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FMZ_QuickActionController.cls
/**
 * Created by samuelmeyers on 11/8/18.
 */

public with sharing class FMZ_QuickActionController {
    private static final String BASE_URL = System.Label.FMZ_Dealer_Community_Base_URL;

    private static List<String> appApprovedStrings = new List<String>{
            'CREDIT APPROVED'
    };
    private static List<String> appInProgressStrings = new List<String>{
            'NEW - ENTERED',
            'NEW - CREDIT PULLED',
            'NEW - IN CREDIT CHECK',
            'NEW - IN REVIEW',
            'NEW - PRICING GENERATED',
            'NEW - CHECKLIST GENERATED'
    };
    private static List<String> qqApprovedStrings = new List<String>{
            'CREDIT APPROVED'
    };

    @AuraEnabled
    public static List<Section> getSections(){
        FMZ_CTA_Settings__c setting = FMZ_CTA_Settings__c.getOrgDefaults();
        List<Section> sections = new List<Section>();
        sections.add(new Section(
                setting.Fund_Apps_Image__c,
                'Fund_Applications',
                setting.Fund_Apps_Label__c,
                setting.Fund_Apps_Call_to_Action__c,
                setting.Fund_Apps_Name_Column_Label__c,
                setting.Fund_Apps_Info_Column_Label__c,
                setting.Fund_Apps_Action_Label__c,
                setting.Fund_Apps_Complete_Message__c));
        sections.add(new Section(
                setting.Complete_Apps_Image__c,
                'Complete_Applications',
                setting.Complete_Apps_Label__c,
                setting.Complete_Apps_Call_to_Action__c,
                setting.Complete_Apps_Name_Column_Label__c,
                setting.Complete_Apps_Info_Column_Label__c,
                setting.Complete_Apps_Action_Label__c,
                setting.Complete_Apps_Complete_Message__c));
        sections.add(new Section(
                setting.Convert_CC_Image__c,
                'Convert_Credit_Checks',
                setting.Convert_CC_Label__c,
                setting.Convert_CC_Call_to_Action__c,
                setting.Convert_CC_Name_Column_Label__c,
                setting.Convert_CC_Info_Column_Label__c,
                setting.Convert_CC_Action_Label__c,
                setting.Convert_CC_Complete_Message__c));

        List<String> appStatus = new List<String>();
        appStatus.addAll(appApprovedStrings);
        appStatus.addAll(appInProgressStrings);

        List<genesis__Applications__c> apps = [
                SELECT Id, Name, genesis__Status__c, genesis__Account__r.Name
                FROM genesis__Applications__c
                WHERE genesis__Status__c IN: appStatus
                ORDER BY LastModifiedDate DESC, genesis__Status__c
        ];

        List<genesis__Quick_Quotes__c> qqs = [
                SELECT Id, Name, genesis__Status__c, genesis__Account__r.Name
                FROM genesis__Quick_Quotes__c
                WHERE genesis__Status__c IN: qqApprovedStrings
                ORDER BY LastModifiedDate DESC, genesis__Status__c
        ];

        List<SectionItem> approvedApps = new List<SectionItem>();
        List<SectionItem> inProgressApps = new List<SectionItem>();

        if(apps.size() > 0){
            for(genesis__Applications__c app : apps){
                if(appApprovedStrings.contains(app.genesis__Status__c)){
                    approvedApps.add(new SectionItem(app.Id, app.Name, BASE_URL+app.Id, app.genesis__Account__r.Name, null, 'Fund'));
                }else{
                    inProgressApps.add(new SectionItem(app.Id, app.Name, BASE_URL+app.Id, app.genesis__Account__r.Name, null, 'View'));
                }
            }
        }

        List<SectionItem> approvedQQs = new List<SectionItem>();
        if(qqs.size() > 0){
            for(genesis__Quick_Quotes__c qq : qqs){
                approvedQQs.add(new SectionItem(qq.Id, qq.Name, BASE_URL+qq.Id, qq.genesis__Account__r.Name, null, 'Convert'));
            }
        }
        
        sections[0].items = approvedApps;
        sections[1].items = inProgressApps;
        sections[2].items = approvedQQs;

        return sections;
    }

    public class Section {
        @AuraEnabled
        public String imageSource;

        @AuraEnabled
        public String name;

        @AuraEnabled
        public String label;

        @AuraEnabled
        public String title;

        @AuraEnabled
        public String linkColTitle;

        @AuraEnabled
        public String infoColTitle;

        @AuraEnabled
        public String actionLabel;

        @AuraEnabled
        public String emptyListMessage;

        @AuraEnabled
        public List<SectionItem> items;

        public Section(String imageSource, String name, String label, String title, String linkColTitle, String infoColTitle, String globalAction, String emptyListMessage){
            this.imageSource = imageSource;
            this.name = name;
            this.label = label;
            this.title = title;
            this.linkColTitle = linkColTitle;
            this.infoColTitle = infoColTitle;
            this.actionLabel = globalAction;
            this.emptyListMessage = emptyListMessage;
            this.items = new List<SectionItem>();
        }

    }

    public class SectionItem {
        @AuraEnabled
        public String id;

        @AuraEnabled
        public String name;

        @AuraEnabled
        public String link;

        @AuraEnabled
        public String info;

        @AuraEnabled
        public String action;

        @AuraEnabled
        public String actionLabel;

        public SectionItem(String id, String name, String link, String info, String action, String actionLabel){
            this.id = id;
            this.name = name;
            this.link = link;
            this.info = info;
            this.action = action;
            this.actionLabel = actionLabel;
        }
    }
}