force-app/main/default/objects/Int_OLMN_Net_Investment__c/Int_OLMN_Net_Investment__c.object-meta.xml
<CustomObject>
    <description>This contains interface net investment subledger information headed to newco oracle</description>
    <label>Int OLMN Net Investment</label>
    <nameField>
        <displayFormat>NI-{00000000}</displayFormat>
        <label>Int OLMN Net Investment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int OLMN Net Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/ACCOUNTING_YIELD__c.field-meta.xml
<CustomField>
    <fullName>ACCOUNTING_YIELD__c</fullName>
    <label>ACCOUNTING YIELD</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/BILLED_UNPAID_REC__c.field-meta.xml
<CustomField>
    <fullName>BILLED_UNPAID_REC__c</fullName>
    <description>Billed but not paid Rent.</description>
    <inlineHelpText>Billed but not paid Rent.</inlineHelpText>
    <label>BILLED UNPAID REC</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/BOOKED_RESIDUAL__c.field-meta.xml
<CustomField>
    <fullName>BOOKED_RESIDUAL__c</fullName>
    <label>BOOKED RESIDUAL</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/CAP_BROKER_FEE_AMOUNT__c.field-meta.xml
<CustomField>
    <fullName>CAP_BROKER_FEE_AMOUNT__c</fullName>
    <label>CAP BROKER FEE AMOUNT</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/CAP_OTHER_FEE_AMOUNT__c.field-meta.xml
<CustomField>
    <fullName>CAP_OTHER_FEE_AMOUNT__c</fullName>
    <label>CAP OTHER FEE AMOUNT</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/CONTRACT_END_DATE__c.field-meta.xml
<CustomField>
    <fullName>CONTRACT_END_DATE__c</fullName>
    <label>CONTRACT END DATE</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/CONTRACT_NUMBER__c.field-meta.xml
<CustomField>
    <fullName>CONTRACT_NUMBER__c</fullName>
    <description>CONTRACT NUMBER</description>
    <label>CONTRACT_NUMBER</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/CONTRACT_START_DATE__c.field-meta.xml
<CustomField>
    <fullName>CONTRACT_START_DATE__c</fullName>
    <label>CONTRACT START DATE</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/CONTRACT_STATUS__c.field-meta.xml
<CustomField>
    <fullName>CONTRACT_STATUS__c</fullName>
    <description>CONTRACT STATUS</description>
    <label>CONTRACT STATUS</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/CONTRACT_TERM__c.field-meta.xml
<CustomField>
    <fullName>CONTRACT_TERM__c</fullName>
    <description>CONTRACT TERM</description>
    <label>CONTRACT TERM</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/EQUIPMENT_COST_CORP__c.field-meta.xml
<CustomField>
    <fullName>EQUIPMENT_COST_CORP__c</fullName>
    <label>EQUIPMENT COST CORP</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/EQUIPMENT_COST_FED__c.field-meta.xml
<CustomField>
    <fullName>EQUIPMENT_COST_FED__c</fullName>
    <label>EQUIPMENT COST FED</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/FIN_PRODUCT__c.field-meta.xml
<CustomField>
    <fullName>FIN_PRODUCT__c</fullName>
    <label>FIN PRODUCT</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/FROZEN_LEASE_INCOME__c.field-meta.xml
<CustomField>
    <fullName>FROZEN_LEASE_INCOME__c</fullName>
    <label>FROZEN LEASE INCOME</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/FROZEN_RESIDUAL_INCOME__c.field-meta.xml
<CustomField>
    <fullName>FROZEN_RESIDUAL_INCOME__c</fullName>
    <description>Total Receivable amount</description>
    <inlineHelpText>Total Receivable amount</inlineHelpText>
    <label>FROZEN RESIDUAL INCOME</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/GROSS_RECEIVABLES__c.field-meta.xml
<CustomField>
    <fullName>GROSS_RECEIVABLES__c</fullName>
    <label>GROSS RECEIVABLES</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/HARD_COST__c.field-meta.xml
<CustomField>
    <fullName>HARD_COST__c</fullName>
    <defaultValue>0</defaultValue>
    <label>HARD COST</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/LEASE_TYPE__c.field-meta.xml
<CustomField>
    <fullName>LEASE_TYPE__c</fullName>
    <label>LEASE TYPE</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/LESSEE_NAME__c.field-meta.xml
<CustomField>
    <fullName>LESSEE_NAME__c</fullName>
    <label>LESSEE NAME</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/LESSEE_NUMBER__c.field-meta.xml
<CustomField>
    <fullName>LESSEE_NUMBER__c</fullName>
    <label>LESSEE NUMBER</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/MONEY_ON_ACCOUNT__c.field-meta.xml
<CustomField>
    <fullName>MONEY_ON_ACCOUNT__c</fullName>
    <description>On Account Cash.</description>
    <inlineHelpText>On Account Cash.</inlineHelpText>
    <label>MONEY ON ACCOUNT</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/MTD_LEASE_INCOME__c.field-meta.xml
<CustomField>
    <fullName>MTD_LEASE_INCOME__c</fullName>
    <description>Value for the current period</description>
    <inlineHelpText>Value for the current period</inlineHelpText>
    <label>MTD LEASE INCOME</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/MTD_RESIDUAL_INCOME__c.field-meta.xml
<CustomField>
    <fullName>MTD_RESIDUAL_INCOME__c</fullName>
    <description>Value for current period</description>
    <label>MTD RESIDUAL INCOME</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/PARTIAL_TERMINATION_YN__c.field-meta.xml
<CustomField>
    <fullName>PARTIAL_TERMINATION_YN__c</fullName>
    <description>If there exists a record in Contract_Equipment__C with status__C as TERMINATED and contract status as Active, then Y else N</description>
    <label>PARTIAL TERMINATION YN</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/PAYMENT_FREQUENCY__c.field-meta.xml
<CustomField>
    <fullName>PAYMENT_FREQUENCY__c</fullName>
    <description>M for Monthly
A for Annual
S for Semi-Annual</description>
    <inlineHelpText>M for Monthly
A for Annual
S for Semi-Annual</inlineHelpText>
    <label>PAYMENT FREQUENCY</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/PERIOD_DATE__c.field-meta.xml
<CustomField>
    <fullName>PERIOD_DATE__c</fullName>
    <description>End Date of the current period in YYYYMMDD Format.</description>
    <label>PERIOD DATE</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/PRIVATE_LABEL__c.field-meta.xml
<CustomField>
    <fullName>PRIVATE_LABEL__c</fullName>
    <label>PRIVATE LABEL</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/REBOOKED_YN__c.field-meta.xml
<CustomField>
    <fullName>REBOOKED_YN__c</fullName>
    <description>Y or N</description>
    <label>REBOOKED YN</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/REMAINING_PAYMENTS__c.field-meta.xml
<CustomField>
    <fullName>REMAINING_PAYMENTS__c</fullName>
    <label>REMAINING PAYMENTS</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/REPORTING_ENTITY__c.field-meta.xml
<CustomField>
    <fullName>REPORTING_ENTITY__c</fullName>
    <defaultValue>&#39;00101&#39;</defaultValue>
    <label>REPORTING ENTITY</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/SBU__c.field-meta.xml
<CustomField>
    <fullName>SBU__c</fullName>
    <defaultValue>&#39;02&#39;</defaultValue>
    <label>SBU</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/SOFT_COST__c.field-meta.xml
<CustomField>
    <fullName>SOFT_COST__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SOFT COST</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/TOT_UNEARNED_LEASE_INCOME__c.field-meta.xml
<CustomField>
    <fullName>TOT_UNEARNED_LEASE_INCOME__c</fullName>
    <description>Sum this amount for all records.</description>
    <inlineHelpText>Sum this amount for all records.</inlineHelpText>
    <label>TOT UNEARNED LEASE INCOME</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/TOT_UNEARNED_RESIDUAL_INCOME__c.field-meta.xml
<CustomField>
    <fullName>TOT_UNEARNED_RESIDUAL_INCOME__c</fullName>
    <label>TOT UNEARNED RESIDUAL INCOME</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/UNBILLED_RECEIVABLE__c.field-meta.xml
<CustomField>
    <fullName>UNBILLED_RECEIVABLE__c</fullName>
    <description>Sum those records where Billed__c is NO or NULL</description>
    <label>UNBILLED RECEIVABLE</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/UNEARNED_LEASE_INCOME__c.field-meta.xml
<CustomField>
    <fullName>UNEARNED_LEASE_INCOME__c</fullName>
    <description>Sum for those records where Accrued_Flag__c is null</description>
    <label>UNEARNED LEASE INCOME</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/UNEARNED_RESIDUAL_INCOME__c.field-meta.xml
<CustomField>
    <fullName>UNEARNED_RESIDUAL_INCOME__c</fullName>
    <description>Value for those records where Accrued_Flag__c is null</description>
    <label>UNEARNED RESIDUAL INCOME</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/UPFRONT_TAX_AMOUNT__c.field-meta.xml
<CustomField>
    <fullName>UPFRONT_TAX_AMOUNT__c</fullName>
    <defaultValue>0</defaultValue>
    <label>UPFRONT TAX AMOUNT</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/VENDOR_NUMBER__c.field-meta.xml
<CustomField>
    <fullName>VENDOR_NUMBER__c</fullName>
    <label>VENDOR NUMBER</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/VENDOR_PROGRAM__c.field-meta.xml
<CustomField>
    <fullName>VENDOR_PROGRAM__c</fullName>
    <label>VENDOR PROGRAM</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/YTD_LEASE_INCOME__c.field-meta.xml
<CustomField>
    <fullName>YTD_LEASE_INCOME__c</fullName>
    <label>YTD LEASE INCOME</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/fields/YTD_RESIDUAL_INCOME__c.field-meta.xml
<CustomField>
    <fullName>YTD_RESIDUAL_INCOME__c</fullName>
    <label>YTD RESIDUAL INCOME</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestNetInvestmentReport.cls
@isTest
public with sharing class TestNetInvestmentReport {
	public static testMethod void testNetInvestmentReport1() {

        // Note: Need residual amount to contract for Net Investment Report,
        // So creating contract directly in test class without TestHelper
		// A. Creating Contract Using TestHelper
        cllease.TestHelper.createSeedDataForTesting();
        // Setting Current System Date in Test Context
        Date currentSystemDate = Date.newInstance(2018, 03, 31);
        // 1. Pre-Setup
        clcommon__Fee_Definition__c  dummyFee   = cllease.Testhelper.createLeaseFee();
        clcommon__Fee_Set__c  dummyFeeSet       = cllease.Testhelper.createLeaseFeeSet();
        insert new clcommon__Fee_Junction__c( clcommon__Fee__c = dummyFee.ID, 
                                              clcommon__Fee_Set__c  = dummyFeeSet.ID);

        cllease__Office_Name__c dummyOffice     = cllease.TestHelper.createOffice('Test Office', true);
        dummyOffice.cllease__Current_System_Date__c = currentSystemDate;
        dummyOffice.Dll_Seg1_Company__c         = '00101';
        dummyOffice.Dll_Seg2_Business_Unit__c   = '02';
        dummyOffice.Dll_Seg3_Department__c      = '3030';
        dummyOffice.Dll_Seg6__c                 = '00000';
        dummyOffice.Dll_Seg7__c                 = '0000';
        update dummyOffice;

        TestData.createPeriodsFor2018(dummyOffice.cllease__Calendar__c);

        Account dummyAccount = new Account(Name = 'Sample Account');
        insert dummyAccount;

        // 2. Creating Sample Product with rental and Dep Streams enabled
        cllease__Lease_Product__c dummyLP    = cllease.TestHelper.createLeaseProduct(dummyOffice, dummyFeeSet);
        dummyLP.cllease__Product_Sub_Type__c = cllease.LendingConstants.PRODUCT_SUB_TYPE_FN_LEASE;
        dummyLP.cllease__Use_Open_Acct_Period__c = true;
        update dummyLP;

        clcommon__Agreement__c dealerProgram =new clcommon__Agreement__c(Name='NewCo');
        insert dealerProgram;

        // 3.Creating Contract
        Date currentDate = Date.newInstance(2018, 01, 01);
        cllease__Lease_Account__c leaseAccount      = new cllease__Lease_Account__c();
        leaseaccount.cllease__Account__c            = dummyAccount.ID;
        leaseAccount.cllease__Lease_Product_Name__c = dummyLP.ID;
        leaseAccount.cllease__Contract_Date__c      = currentDate;
        leaseaccount.cllease__Financed_Amount__c    = 10000;
        leaseaccount.cllease__Residual_Amount__c    = 1000;
        leaseAccount.cllease__Term__c               = 12;
        leaseaccount.Dealer_Program__c              = dealerProgram.Id;

        // 3.a Adding Equipments to Contract
        List<cllease__Contract_Equipment__c> contractEquipments = new List<cllease__Contract_Equipment__c>();
        contractEquipments.add(new cllease__Contract_Equipment__c(cllease__Estimated_Selling_Price__c = 10000, cllease__Residual_Amount__c = 1000));
      
        // 3.b Adding Payment Schedules to Contract
        List<cllease__Payment_Schedule__c> paymentDetails =  new List<cllease__Payment_Schedule__c>();
        paymentDetails.add(new cllease__Payment_Schedule__c(cllease__Sequence__c = 1, cllease__Number_Of_Payments__c = 12,
                           cllease__Frequency__c = cllease.LendingConstants.PAYMENT_FREQ_MONTHLY,
                           cllease__Payment_Amount__c = 1200, cllease__Payment_Date__c = currentDate,
                           cllease__Total_Payment__c = 1200));

        // 4. Calling ContractBuilder for Contract Creation
        cllease.ContractBuilder builder = new cllease.ContractBuilder(leaseAccount);
        builder.addChildObjects(contractEquipments);
        builder.addChildObjects(paymentDetails);
        String response = builder.createContract(cllease.LendingConstants.ContractCreateOption.ACTIVATECONTRACT);

        cllease__Lease_Account__c contract = builder.getContract();
        // Validating Contract Activation
        String contractStatus = 'ACTIVE - GOOD STANDING';
        System.assert(contractStatus.containsIgnoreCase(contract.cllease__Lease_Status__c));

        // B. Adding accounting configuration to Product and Creating other setup
        cllease__Lease_Product__c product = [SELECT Id, Name From cllease__Lease_Product__c Limit 1];
        cllease__Office_Name__c company = [SELECT Id, Name From cllease__Office_Name__c Where Name = 'Test Office'];

        TestData.doPreSetup();
        TestData.createAccountingTemplateSetup(product.Id, company.Id);
        // Creating and runnning the Batch jobs for General Entries Creation.
        System.Test.startTest();
            // Creating DAG
            String dagName = 'CLLease-BatchTestDAG';
            List<String> listOfJobs = new List<String>{ 'cllease.BillGeneratorJob',  'cllease.BillDetailGeneratorJob',
                                        'GLTxnGeneratorJob', 'NetInvestmentReportGeneratorJob', 'CloseAccountingPeriodsJob'};
            TestHelper.createDAGSpecificJobs(listOfJobs, dagName);
            // Running DAG
            TestHelper.runDAG(dagName);
        System.Test.stopTest();

        List<Int_OLMN_Net_Investment__c> netInvReport = [Select Id, Name,
                                                            ACCOUNTING_YIELD__C,
                                                            BILLED_UNPAID_REC__C,
                                                            BOOKED_RESIDUAL__C ,
                                                            CAP_BROKER_FEE_AMOUNT__C,
                                                            CAP_OTHER_FEE_AMOUNT__C,
                                                            CONTRACT_END_DATE__C,
                                                            CONTRACT_NUMBER__C,
                                                            CONTRACT_START_DATE__C,
                                                            CONTRACT_STATUS__C,
                                                            CONTRACT_TERM__C,
                                                            EQUIPMENT_COST_CORP__C,
                                                            EQUIPMENT_COST_FED__C,
                                                            FIN_PRODUCT__C,
                                                            FROZEN_LEASE_INCOME__C,
                                                            FROZEN_RESIDUAL_INCOME__C,
                                                            GROSS_RECEIVABLES__C,
                                                            HARD_COST__C,
                                                            LEASE_TYPE__C,
                                                            LESSEE_NAME__C,
                                                            LESSEE_NUMBER__C,
                                                            MONEY_ON_ACCOUNT__C,
                                                            MTD_LEASE_INCOME__C,
                                                            MTD_RESIDUAL_INCOME__C,
                                                            PARTIAL_TERMINATION_YN__C,
                                                            PAYMENT_FREQUENCY__C,
                                                            PERIOD_DATE__C,
                                                            PRIVATE_LABEL__C, 
                                                            REBOOKED_YN__C,
                                                            REMAINING_PAYMENTS__C,
                                                            REPORTING_ENTITY__C,
                                                            SBU__C,
                                                            SOFT_COST__C,
                                                            TOT_UNEARNED_LEASE_INCOME__C,
                                                            TOT_UNEARNED_RESIDUAL_INCOME__C,
                                                            UNBILLED_RECEIVABLE__C,
                                                            UNEARNED_LEASE_INCOME__C,
                                                            UNEARNED_RESIDUAL_INCOME__C,
                                                            UPFRONT_TAX_AMOUNT__C,
                                                            VENDOR_NUMBER__C,
                                                            VENDOR_PROGRAM__C, 
                                                            YTD_LEASE_INCOME__C,
                                                            YTD_RESIDUAL_INCOME__C
                                                            From Int_OLMN_Net_Investment__c
                                                            Order by Name];

        System.debug(LoggingLevel.ERROR, ' Net investment report: '+netInvReport);
	}

	public static testMethod void testNetInvestmentReportNegative() {
		// A. Creating Contract Using TestHelper
        cllease__Lease_Account__c contract = TestHelper.createContract();
        String contractStatus = 'ACTIVE - GOOD STANDING';
        System.assert(contractStatus.containsIgnoreCase(contract.cllease__Lease_Status__c));

        // Deleting all periods to catch exception
        delete [SELECT Id, Name, cllease__Status__c FROM cllease__Period_Status__c]; 

        // Creating and runnning the Batch jobs for General Entries Creation.
        System.Test.startTest();
        	List<String> contractNames = new List<String>{contract.Name};
            NetInvestmentReportGeneratorJob job = new NetInvestmentReportGeneratorJob(contractNames, null);
			Database.executeBatch(job);
        System.Test.stopTest();

        // Following api call just to coverage code.
        CLSCustomUtil.getStringsFromList(new List<String>{contract.Name});

        cllease__Batch_Process_Log__c log = [Select Id, cllease__message__c From cllease__Batch_Process_Log__c Limit 1];
        System.debug(LoggingLevel.ERROR, ' actual error message: '+ log);
        String expectedMessage = 'Error is No Open Period available';
        System.assert(log.cllease__message__c.contains(expectedMessage), 'Mismatch in thrown Exception.');
	}
}