force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{000000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Bill_To_Usage__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Usage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bill To Usage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Install_At__c.field-meta.xml
<CustomField>
    <fullName>Install_At__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Install At</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Primary_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Address</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Address__c/recordTypes/Lessee.recordType-meta.xml
<RecordType>
    <fullName>Lessee</fullName>
    <active>true</active>
    <label>Lessee</label>
</RecordType>

force-app/main/default/classes/TestPrimaryAddressUpdate.cls
/**
 * Owner: Cloud Lending Solutions
 * Usage: Following Test class helps in testing the primary address update functionality
 *      
 **/
@isTest
public with sharing class TestPrimaryAddressUpdate {
	
	@isTest
	public static void testAccountPrimaryAddressUpdate() {
		// Creating Account with Lessee type
		RecordType lessee 	= [SELECT Id FROM RecordType WHERE DeveloperName = 'Lessee'AND SobjectType = 'Account'AND IsActive = true limit 1];                                    
        Account a 			= genesis.TestHelper.createAccount();
        a.RecordTypeId 		= lessee.id;
        upsert a;

        // Creating Address
        RecordType lesseeAdd = [SELECT Id FROM RecordType WHERE DeveloperName = 'Lessee'  AND SobjectType = 'Address__c'  AND IsActive = true limit 1];  
        List<Address__c> addressToInsert = new List<Address__c>(); 
        Address__c address 		= new Address__c();
        address.RecordTypeId 	= lesseeAdd.Id;
        address.Country__c 		= 'USA';
        address.Bill_To_Usage__c= false;
        address.Install_At__c 	= true;
        address.Primary_Address__c = true;
        address.Account__c 		= a.Id;
        addressToInsert.add(address);

        Address__c address2 		= new Address__c();
        address2.RecordTypeId 		= lesseeAdd.Id;
        address2.Country__c 		= 'USA';
        address2.Bill_To_Usage__c 	= true;
        address2.Install_At__c 		= false;
        address2.Account__c 		= a.Id;
        addressToInsert.add(address2);

        insert addressToInsert;

        // validating address's primary address field
        Id accId = a.Id;
        Account accountToValidate = [SELECT Id, Primary_Address__c FROM Account Where Id = :accId];
        System.debug(LoggingLevel.ERROR, ' account details: '+accountToValidate);

        System.assert(accountToValidate.Primary_Address__c == address.Id);

	}
}