force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{000000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Bill_To_Usage__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Usage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bill To Usage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Install_At__c.field-meta.xml
<CustomField>
    <fullName>Install_At__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Install At</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Primary_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Address</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Validation_Status__c.field-meta.xml
<CustomField>
    <fullName>Validation_Status__c</fullName>
    <label>Validation Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Validation_Time_Stamp__c.field-meta.xml
<CustomField>
    <fullName>Validation_Time_Stamp__c</fullName>
    <label>Validation Time Stamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/FMZ_NewAddressController.cls
/**
 * Created by samuelmeyers on 11/12/18.
 */

public without sharing class FMZ_NewAddressController {

    @AuraEnabled
    public static Address__c getAddress(Id recordId){
        Address__c addr = new Address__c();

        if(recordId != null){
            if(recordId.getSobjectType() == Account.sObjectType){
                addr.Account__c = recordId;
            }else if(recordId.getSobjectType() == Address__c.sObjectType){
                addr = [
                        SELECT Id, Account__c, Address_Line_1__c, Address_Line_2__c, City__c, County__c, Country__c, State__c,
                                Zip_Code__c, Validation_Time_Stamp__c, Validation_Status__c, Bill_To_Usage__c, Primary_Address__c,
                                Install_At__c
                        FROM Address__c
                        WHERE Id=:recordId
                ];
            }
        }
        return addr;
    }

    @AuraEnabled
    public static List<FMZ_EDQ_Address_Callout.Match> getMatches(String addressString){
        return FMZ_EDQ_Address_Callout.getAddressMatches(addressString);
    }

    @AuraEnabled
    public static FMZ_EDQ_Address_Callout.Address getFormat(String formatUrl){
        return FMZ_EDQ_Address_Callout.getAddressFormat(formatUrl);
    }

    @AuraEnabled
    public static void createAddress(Address__c address){
        address.Install_At__c = true;
        insert address;
    }
}