force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{000000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Address__c/recordTypes/Dealer.recordType-meta.xml
<RecordType>
    <fullName>Dealer</fullName>
    <active>true</active>
    <label>Dealer</label>
</RecordType>

force-app/main/default/classes/ExperianDataQuality_AddressTriggerTest.cls
@isTest
public with sharing class ExperianDataQuality_AddressTriggerTest {
    public static testmethod void insertAddressTest() {

        RecordType recordType = [SELECT Id FROM RecordType WHERE Name = 'Dealer' AND SobjectType = 'Address__c' LIMIT 1];
            
        Account acc = new Account(Name = 'John Smith', BillingStreet = '445 Hamilton Ave', ShippingStreet = '445 Hailton');
        insert acc;
        
        Address__c address = new Address__c(RecordTypeId = recordType.Id, Account__c = acc.Id);
        insert address;
        
        address.City__c = 'London';
        update address;
        
        // Using Assert to avoid Checkmarx flagging this as a code quality problem.
        // It's difficult to implement a real Unit test for this trigger, as it depends on EDQ configuration.
        System.assertEquals('London', address.City__c);
    }
}