force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{000000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Primary_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Address</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/FMZ_Customer_NewCustomerController.cls
public with sharing class FMZ_Customer_NewCustomerController {

    public static final String CUSTOMER_OBJECT = 'Account';

    @AuraEnabled
    public static List<FMZ_CommunityServices.FieldSetMember> getCustomerFields(String fieldsetName) {

        return FMZ_CommunityServices.getFieldSetMembers(CUSTOMER_OBJECT, fieldSetName);

    }

    @AuraEnabled
    public static Id submitAccount(Account acc, Address__c address) {
        Savepoint sp = Database.setSavepoint();
        try{
            insert acc;
            if(address != null){
                address.Account__c = acc.Id;
                address.Primary_Address__c = true;
                insert address;
                acc.Primary_Address__c = address.Id;
                update acc;
            }
            return acc.Id;
        }catch(exception e){

        }
        return null;
    }

}