force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{000000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Primary_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Address</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PrimaryAddressUpdateUtil.cls
/**
 * Owner: Cloud Lending Solutions
 * Usage: Following Future utility helps in resetting primary address flag for  the non primary address records.
 *      
 **/
global with sharing class PrimaryAddressUpdateUtil {
	
	@future
	public static void processRecords(List<ID> accIdSet) {
		// Retrieving all addresses linked from accounts
		if(accIdSet.size() > 0) {
			List<Address__c> addressToUpdate = new List<Address__c>();
			List<Account> accountsWithAddresses = [Select Id, Name, Primary_Address__c,
														(Select Id, Name, Account__c, Primary_Address__c
														From Addresses__r)
													From Account 
													Where Id IN :accIdSet];


			for(Account acc : accountsWithAddresses) {
				for(Address__c address : acc.Addresses__r) {
					// check for non primary addresses and update the primary flag as false
					if(acc.Primary_Address__c != address.Id) {
						address.Primary_Address__c = false;
						addressToUpdate.add(address);
					}
				}
			}

			// update addresses for primary field flag update
			if(addressToUpdate.size() > 0) {
				update addressToUpdate;
			}
		}
	}
}