force-app/main/default/objects/Int_Agreement__c/Int_Agreement__c.object-meta.xml
<CustomObject>
    <description>Int Agreement</description>
    <label>Int Agreement</label>
    <nameField>
        <displayFormat>AGR-{0000000000}</displayFormat>
        <label>Agreement Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Agreement__c/fields/Arrears_Amount__c.field-meta.xml
<CustomField>
    <fullName>Arrears_Amount__c</fullName>
    <description>Arrears Amount</description>
    <label>Arrears Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Int_Agreement__c/fields/Net_Principal_Balance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Net_Principal_Balance_Amount__c</fullName>
    <description>Net Principal Balance Amount</description>
    <label>Net Principal Balance Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Int_Agreement__c/fields/Residual_Value_Booked__c.field-meta.xml
<CustomField>
    <fullName>Residual_Value_Booked__c</fullName>
    <description>Residual Value Booked</description>
    <label>Residual Value Booked</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Int_Agreement_Exposure__c/Int_Agreement_Exposure__c.object-meta.xml
<CustomObject>
    <description>Int Agreement Exposure</description>
    <label>Int Agreement Exposure</label>
    <nameField>
        <displayFormat>AGE-{0000000000}</displayFormat>
        <label>Agreement Exposure Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Agreements Exposure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Agreement_Exposure__c/fields/Exposure_Booked__c.field-meta.xml
<CustomField>
    <fullName>Exposure_Booked__c</fullName>
    <description>Exposure Booked</description>
    <label>Exposure Booked</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Int_Agreement_Interest__c/Int_Agreement_Interest__c.object-meta.xml
<CustomObject>
    <description>Int Agreement Interest</description>
    <label>Int Agreement Interest</label>
    <nameField>
        <displayFormat>AGI-{0000000000}</displayFormat>
        <label>Agreement Interest Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Agreements Interest</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Agreement_Interest__c/fields/Interest_Amount__c.field-meta.xml
<CustomField>
    <fullName>Interest_Amount__c</fullName>
    <description>Interest Amount</description>
    <label>Interest Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Int_Agreement_Line__c/Int_Agreement_Line__c.object-meta.xml
<CustomObject>
    <description>Int Agreement Line</description>
    <label>Int Agreement Line</label>
    <nameField>
        <displayFormat>ALI-{0000000000}</displayFormat>
        <label>Agreement Line Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Agreement Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Agreement_Line__c/fields/Net_Principal_Balance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Net_Principal_Balance_Amount__c</fullName>
    <description>Net Principal Balance Amount</description>
    <label>Net Principal Balance Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Int_Agreement_Line__c/fields/Residual_Value_Booked__c.field-meta.xml
<CustomField>
    <fullName>Residual_Value_Booked__c</fullName>
    <description>Residual Value Booked</description>
    <label>Residual Value Booked</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Int_Agreement_Line_Feature__c/Int_Agreement_Line_Feature__c.object-meta.xml
<CustomObject>
    <description>Int Agreement Line Feature</description>
    <label>Int Agreement Line Feature</label>
    <nameField>
        <displayFormat>AFI-{0000000000}</displayFormat>
        <label>Agreement Feature Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Agreement Line Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Agreement_Non_IFRS__c/Int_Agreement_Non_IFRS__c.object-meta.xml
<CustomObject>
    <description>Int Agreement Non IFRS</description>
    <label>Int Agreement Non IFRS</label>
    <nameField>
        <displayFormat>ANI-{0000000000}</displayFormat>
        <label>Agreement Non IFRS Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Agreements Non IFRS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Agreement_Non_IFRS__c/fields/Arrears_Amount__c.field-meta.xml
<CustomField>
    <fullName>Arrears_Amount__c</fullName>
    <description>Arrears Amount</description>
    <label>Arrears Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Int_Agreement_Party__c/Int_Agreement_Party__c.object-meta.xml
<CustomObject>
    <description>Int Agreement Party</description>
    <label>Int Agreement Party</label>
    <nameField>
        <displayFormat>API-{0000000000}</displayFormat>
        <label>Agreement Party Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Agreements Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Agreement_Party__c/fields/Party_Number__c.field-meta.xml
<CustomField>
    <fullName>Party_Number__c</fullName>
    <description>Agreement Number</description>
    <label>Party Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_Agreement_Payment_Schedule__c/Int_Agreement_Payment_Schedule__c.object-meta.xml
<CustomObject>
    <description>Int Agreement Payment Schedule</description>
    <label>Int Agreement Payment Schedule</label>
    <nameField>
        <displayFormat>APS-{0000000000}</displayFormat>
        <label>Agreement Payment Schedule Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Agreements Payment Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Agreement_Payment_Schedule__c/fields/Schedule_Amount__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Amount__c</fullName>
    <description>Schedule Amount</description>
    <label>Schedule Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Int_Agreement_Provision__c/Int_Agreement_Provision__c.object-meta.xml
<CustomObject>
    <description>Int Agreement Provision</description>
    <label>Int Agreement Provision</label>
    <nameField>
        <displayFormat>AGP-{0000000000}</displayFormat>
        <label>Agreement Provision Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Agreements Provision</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Asset__c/Int_Asset__c.object-meta.xml
<CustomObject>
    <description>Int Asset</description>
    <label>Int Asset</label>
    <nameField>
        <displayFormat>AST-{0000000000}</displayFormat>
        <label>Asset Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Asset_Feature__c/Int_Asset_Feature__c.object-meta.xml
<CustomObject>
    <description>Int Asset Feature</description>
    <label>Int Asset Feature</label>
    <nameField>
        <displayFormat>ASF-{0000000000}</displayFormat>
        <label>Asset Feature Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Asset Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Asset_Usage__c/Int_Asset_Usage__c.object-meta.xml
<CustomObject>
    <description>Int Asset Usage</description>
    <label>Int Asset Usage</label>
    <nameField>
        <displayFormat>AUI-{0000000000}</displayFormat>
        <label>Asset Usage Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Asset Usages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Delivery_Control__c/Int_Delivery_Control__c.object-meta.xml
<CustomObject>
    <description>Int Delivery Control</description>
    <label>Int Delivery Control</label>
    <nameField>
        <displayFormat>DEL-{0000000000}</displayFormat>
        <label>Delivery Control Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Delivery Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Facility__c/Int_Facility__c.object-meta.xml
<CustomObject>
    <description>Int Facility Object</description>
    <label>Int Facility</label>
    <nameField>
        <displayFormat>Fac-{0000000000}</displayFormat>
        <label>Facility Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Facility_Feature__c/Int_Facility_Feature__c.object-meta.xml
<CustomObject>
    <description>Int Facility Feature</description>
    <label>Int Facility Feature</label>
    <nameField>
        <displayFormat>FFI-{0000000000}</displayFormat>
        <label>Facility Feature Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Facility Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Facility_Party__c/Int_Facility_Party__c.object-meta.xml
<CustomObject>
    <description>Int Facility Party</description>
    <label>Int Facility Party</label>
    <nameField>
        <displayFormat>FPI-{0000000000}</displayFormat>
        <label>Facility Party Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Facility Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Facility_Party__c/fields/Party_Number__c.field-meta.xml
<CustomField>
    <fullName>Party_Number__c</fullName>
    <description>Party Number</description>
    <label>Party Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_File_Control__c/Int_File_Control__c.object-meta.xml
<CustomObject>
    <description>Int File Control</description>
    <label>Int File Control</label>
    <nameField>
        <displayFormat>FCI-{0000000000}</displayFormat>
        <label>File Control Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Files Control</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_File_Control__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <description>File Name</description>
    <label>File Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_Party__c/Int_Party__c.object-meta.xml
<CustomObject>
    <description>Int Party</description>
    <label>Int Party</label>
    <nameField>
        <displayFormat>PAR-{0000000000}</displayFormat>
        <label>Party Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Party__c/fields/Party_Number__c.field-meta.xml
<CustomField>
    <fullName>Party_Number__c</fullName>
    <description>Party Number</description>
    <label>Party Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Int_Party_External_Reference__c/Int_Party_External_Reference__c.object-meta.xml
<CustomObject>
    <description>Int Party External Reference</description>
    <label>Int Party External Reference</label>
    <nameField>
        <displayFormat>PER-{0000000000}</displayFormat>
        <label>Party External Reference Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Party External References</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Party_External_Reference__c/fields/Party_Number__c.field-meta.xml
<CustomField>
    <fullName>Party_Number__c</fullName>
    <description>Party Number</description>
    <label>Party Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Int_Party_Feature__c/Int_Party_Feature__c.object-meta.xml
<CustomObject>
    <description>Int Party Feature</description>
    <label>Int Party Feature</label>
    <nameField>
        <displayFormat>PFI-{0000000000}</displayFormat>
        <label>Party Feature Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Party Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Party_Feature__c/fields/Party_Number__c.field-meta.xml
<CustomField>
    <fullName>Party_Number__c</fullName>
    <description>Party Number</description>
    <label>Party Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_Party_Street_Address__c/Int_Party_Street_Address__c.object-meta.xml
<CustomObject>
    <description>Int Party Street Address</description>
    <label>Int Party Street Address</label>
    <nameField>
        <displayFormat>PSA-{0000000000}</displayFormat>
        <label>Party Street Address Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Party Street Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Risk_Costs_Movements__c/Int_Risk_Costs_Movements__c.object-meta.xml
<CustomObject>
    <description>Int Risk Costs Movements</description>
    <label>Int Risk Costs Movements</label>
    <nameField>
        <displayFormat>RCM-{0000000000}</displayFormat>
        <label>Risk Costs Movements ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Risk Costs Movements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DMBIInterfaceDAGJob.cls
/**
 * Following job helps in cleaning up the DMBI table records 
 * Which runs through multiple instances 
 **/

 global class DMBIInterfaceDAGJob extends clcommon.DynamicJob {

    private static String query;
    private static final String JOB_NAME = 'DMBI Interface DAG Job';
    //query String
    public static Map<String,String> intCodeMapping  = new Map<String, String>();
    public static Set<String> dataObjSet;
    public Map<String, integer> sobjectCountMap      = new Map<String, Integer>();
    global Map<string,List<Integer>> sobjectHashMap  = new Map<string, List<Integer>>();
    public Boolean isSuccess = true;
    public Datetime batchStartTime = System.now();  
    public Map<String, Int_Party__c> insertedPartiesMap = new Map<String, Int_Party__c>();  
    public Decimal ScheduleAmount=0;
    public Decimal ExposureBooked=0;
    public Decimal InterestAmount=0;
    public Decimal ResidualValueBooked = 0;
    public Decimal NetPrincipleBalanceAmount = 0;
    public Decimal ArrearsAmount = 0;
    
    global DMBIInterfaceDAGJob() {
        super(JOB_NAME, initialize());
        doInitialize();
    }
    
    global virtual override String getRuntimeQuery() {
        System.debug(LoggingLevel.ERROR, 'DMBIInterfaceDAGJob in getRuntimeQuery : ' + query);
        return query; 
    }
    
    public static String initialize() {
        // Retrieving the Mapping 
        intCodeMapping  = DMBIInterfaceRecordUtil.getIntMapping();
        // initializing the data sets
        dataObjSet      = DMBIConstants.dataObjectSet;
        // Constructing query for job
        query = DMBIConstants.DMBIQueryStr;

        System.debug(LoggingLevel.ERROR, 'DMBIInterfaceDAGJob query in initialize : ' + query);
        return query;
    }
    
    /**
     * Following method helps in running the batches for batch job
     **/
    public override void doExecute(Database.BatchableContext bc, List<sObject> scope) {
 		//isSuccess = true;
        List<cllease__Lease_Account__c> contracts = (List<cllease__Lease_Account__c>)scope;
        List<sobject> agreementsToInsert = new List<sobject>();
        List<sobject> agreementsToInsert1 = new List<sobject>();
        List<sobject> agreementsToInsert2 = new List<sobject>();
        List<sobject> agreementsToInsert3 = new List<sobject>();
        List<sobject> agreementsToInsert4 = new List<sobject>();
        List<sobject> agreementsToInsert5 = new List<sobject>();
        List<sobject> agreementsToInsert6 = new List<sobject>();
        List<sobject> agreementsToInsert7 = new List<sobject>();
        //List<sobject> agreementsToInsert8 = new List<sobject>();
        Savepoint sp = database.setsavepoint();        
        try {
            //system.debug('contracts-->'+contracts);
            if(!scope.isEmpty()){
                
                //Creating AGREEMENTS report 
                List<Int_Agreement__c> agreementRecords = DMBIInterfaceRecordUtil.CreateAgreements(contracts, IntCodeMapping);
                constructControlMap('Int_Agreement__c', DMBIInterfaceRecordUtil.CountInsertedRecords(agreementRecords));
                
                if(!agreementRecords.isEmpty()){
                    calculateHashcodeFields((List<sObject>)agreementRecords);

                    List<Int_Asset__c> AssetRecords = DMBIInterfaceRecordUtil.CreateAssets(contracts,IntCodeMapping);
                    constructControlMap('Int_Asset__c',DMBIInterfaceRecordUtil.CountInsertedRecords(AssetRecords));                    
                    if(!AssetRecords.isEmpty()){ 

                        List<Int_Agreement_Line__c> agreementLinesList = DMBIInterfaceRecordUtil.CreateAgreementlines(agreementRecords, contracts, IntCodeMapping); 
                        if(!agreementLinesList.isEmpty()){
                            Database.Insert(AgreementLinesList, false);
                            constructControlMap('Int_Agreement_Line__c',DMBIInterfaceRecordUtil.CountInsertedRecords(agreementLinesList));                            
                            List<sobject> AgrLineAssetsAndCollateralsList = DMBIInterfaceRecordUtil.CreateAgrLineAssetsAndCollaterals(agreementLinesList, contracts, AssetRecords);
                            calculateObjectCount(AgrLineAssetsAndCollateralsList);
                        }
                    }
                }

                if (!agreementRecords.IsEmpty() && !contracts.IsEmpty()){
                    //PARTIES
                    List<Int_Party__c> IntParties = DMBIInterfaceRecordUtil.CreateParties(contracts,insertedPartiesMap.keyset(),IntCodeMapping);
                    //system.debug('IntParties.size()--->'+IntParties.size());
                    if(!IntParties.isEmpty()){
                        constructControlMap('Int_Party__c',DMBIInterfaceRecordUtil.CountInsertedRecords(IntParties));//  
                        UpdateInsertedParties(IntParties);  
                    }
                    
                    agreementsToInsert.AddAll(DMBIInterfaceRecordUtil.CreateIntAgreementPaymentSchedules(agreementRecords,contracts,IntCodeMapping));
                    if(!agreementsToInsert.isEmpty()){
                        calculateObjectCount(agreementsToInsert); 
                        calculateHashcodeFields(agreementsToInsert);     
                    }
                    
                    agreementsToInsert1.AddAll(DMBIInterfaceRecordUtil.CreateIntAgreementPartyStreetAddressDetails(IntParties,contracts,IntCodeMapping));

                    agreementsToInsert2.AddAll(DMBIInterfaceRecordUtil.CreateIntAgreementParties(agreementRecords,contracts,IntParties,insertedPartiesMap.values(),IntCodeMapping));
                    
                    agreementsToInsert3.AddAll(DMBIInterfaceRecordUtil.CreateAgreementInterests(agreementRecords,contracts));
                    if(!agreementsToInsert3.isEmpty()){
                        calculateObjectCount(agreementsToInsert3);  
                        calculateHashcodeFields(agreementsToInsert3);     
                    }
                    agreementsToInsert4.AddAll(DMBIInterfaceRecordUtil.CreateAgreementFeatures(agreementRecords,contracts,IntCodeMapping));
                    if(!agreementsToInsert4.isEmpty()){
                        calculateObjectCount(agreementsToInsert4);    
                    }

                    agreementsToInsert5.AddAll(DMBIInterfaceRecordUtil.CreateIntAgreementPartyExternalReferences(IntParties,contracts,IntCodeMapping));
                    if(!agreementsToInsert5.isEmpty()){
                        calculateHashcodeFields(agreementsToInsert5); 
                    }

                    agreementsToInsert6.AddAll(DMBIInterfaceRecordUtil.CreateAgreementClassifications(agreementRecords,contracts,IntCodeMapping));
                    if(!agreementsToInsert6.isEmpty()){
                        calculateObjectCount(agreementsToInsert6);    
                    }

                    agreementsToInsert7.AddAll(DMBIInterfaceRecordUtil.CreateAgreementExposures(agreementRecords,contracts,IntCodeMapping));                 
                    if(!agreementsToInsert7.isEmpty()){
                        calculateObjectCount(agreementsToInsert7);  
                        calculateHashcodeFields(agreementsToInsert7);     
                    }
                }
            }

            if(!agreementsToInsert.isEmpty()){
                Insert agreementsToInsert;
                //system.debug('agreementsToInsert--->'+agreementsToInsert.size());
            }
            if(!agreementsToInsert1.isEmpty()){
                //Insert agreementsToInsert1;
                Database.insert(agreementsToInsert1, false);
                constructControlMap('Int_Party_Street_Address__c',DMBIInterfaceRecordUtil.CountInsertedRecords(agreementsToInsert1));//    
                //system.debug('agreementsToInsert1--->'+agreementsToInsert1.size());
            }
            if(!agreementsToInsert2.isEmpty()){
                Insert agreementsToInsert2;
                //Database.Insert(agreementsToInsert2,false);
                constructControlMap('Int_Agreement_Party__c',DMBIInterfaceRecordUtil.CountInsertedRecords(agreementsToInsert2));//    
                //system.debug('agreementsToInsert2--->'+agreementsToInsert2.size());
            }
            if(!agreementsToInsert3.isEmpty()){
                //Insert agreementsToInsert3;
                database.insert(agreementsToInsert3,false);
                //system.debug('agreementsToInsert3--->'+agreementsToInsert3.size());
            }
            if(!agreementsToInsert4.isEmpty()){
                Insert agreementsToInsert4;
                //system.debug('agreementsToInsert4--->'+agreementsToInsert4.size());
            }
            if(!agreementsToInsert5.isEmpty()){
                //Insert agreementsToInsert5;
                Database.insert(agreementsToInsert5, false);
                constructControlMap('Int_Party_External_Reference__c',DMBIInterfaceRecordUtil.CountInsertedRecords(agreementsToInsert5));
                //system.debug('agreementsToInsert4--->'+agreementsToInsert4.size());
            }
            if(!agreementsToInsert6.isEmpty()){
                Insert agreementsToInsert6;
                //system.debug('agreementsToInsert4--->'+agreementsToInsert4.size());
            }
            if(!agreementsToInsert7.isEmpty()){
                Insert agreementsToInsert7;
                //system.debug('agreementsToInsert4--->'+agreementsToInsert4.size());
            }

        } catch(exception e){
            database.rollback(sp);
            if(!e.getMessage().contains('Party number')){
                isSuccess = false;
            }
            System.debug(LoggingLevel.ERROR, 'DMBIInterfaceDAGJob Exception in execute method : '+e.getMessage());
            System.debug(LoggingLevel.ERROR, 'DMBIInterfaceDAGJob Exception in linenumber : '+e.getLineNumber());
            //insert batch process log for exceptions
            insert new cllease__Batch_Process_Log__c(Name='DMBIInterfaceDAGJob execute() : ', cllease__Date__c = System.today(), 
            cllease__Message__c='Error is '+ ( e.getmessage().length()>255 ? e.getMessage().subString(0,255) : e.getMessage())
            +' in line number: '+ e.getlinenumber());
        }
    }
    
    private void constructControlMap(String ObjectName, integer sizeOfList){
        if(sobjectCountMap.containskey(ObjectName)){
            sobjectCountMap.put(ObjectName, sobjectCountMap.get(ObjectName)+sizeOfList);    
        }
        else{
            sobjectCountMap.put(ObjectName, sizeOfList);
        }
    }
    
    public void calculateObjectCount(List<sobject> SobjectList){
        Map<string,integer> CountMap = new Map<string,integer>();
        //string objname = string.valueof(obj.getSObjectType());
        for(sobject obj:SobjectList){
            if(obj!=Null){
                string objname = string.valueof(obj.getSObjectType()); 
                if(!countMap.containskey(objname)){
                    CountMap.put(objname,1);
                }
                else{
                    CountMap.put(objname,CountMap.get(objname)+1);
                }
            }   
        }
        if(!CountMap.isEmpty()){
            for(string ObjName : CountMap.keyset()){
                constructControlMap(ObjName,CountMap.get(ObjName));
            }
        }
    }

    //Update insertedPartiesMap
    public void UpdateInsertedParties(List<Int_Party__c> Parties){
        If(!Parties.isEmpty()){
            for(Int_Party__c party: Parties){
                If(party.Id != Null){
                    insertedPartiesMap.put(party.Party_Number__c,party);   
                }    
            }    
        } 
    }

    //Calculate Hashtotal1 for file control
    public void calculateHashcodeFields(List<sobject> SobjectList){
        Map<string,string> HashMap = new Map<string,string>();
        
        for(sobject obj:SobjectList){
            string objname = string.valueof(obj.getSObjectType()); 
            if (objname == 'Int_Agreement_Payment_Schedule__c') {
                ScheduleAmount = ScheduleAmount + Integer.valueOf(obj.get('Schedule_Amount__c')); 
            }
            else if (objname == 'Int_Agreement_Exposure__c') {   
                ExposureBooked = ExposureBooked + Integer.valueOf(obj.get('Exposure_Booked__c'));
            }    
            else if (objname == 'Int_Agreement_Interest__c'){    
                InterestAmount = InterestAmount + Integer.valueOf(obj.get('Interest_Amount__c')); 
            }     
            else if (objname == 'Int_Agreement__c')  {  
                ResidualValueBooked = ResidualValueBooked + Integer.valueOf(obj.get('Residual_Value_Booked__c')); 
                NetPrincipleBalanceAmount = NetPrincipleBalanceAmount + Integer.valueOf(obj.get('Net_Principal_Balance_Amount__c'));
                ArrearsAmount = ArrearsAmount + Integer.valueOf(obj.get('Arrears_Amount__c'));
            }       
        } 
    } 

    public void PrepareHashmap(){           
        if (!SobjectHashMap.containskey('Int_Agreement_Payment_Schedule__c')) {
            SobjectHashMap.put('Int_Agreement_Payment_Schedule__c',new List<Integer>{system.hashcode(ScheduleAmount),0,0});
        }                        
        if (!SobjectHashMap.containskey('Int_Agreement_Exposure__c')) {
            SobjectHashMap.put('Int_Agreement_Exposure__c',new List<Integer>{system.hashcode(ExposureBooked),0,0});
        }
        if (!SobjectHashMap.containskey('Int_Agreement_Interest__c')) {
            SobjectHashMap.put('Int_Agreement_Interest__c',new List<Integer>{system.hashcode(InterestAmount),0,0});
        }
        if (!SobjectHashMap.containskey('Int_Agreement__c')) {
            SobjectHashMap.put('Int_Agreement__c',new List<Integer>{system.hashcode(ResidualValueBooked),system.hashcode(NetPrincipleBalanceAmount),system.hashcode(ArrearsAmount)});
        }
    }
    
    public override void doInitialize() { }
    public override void doStart(Database.BatchableContext bc) { }

	public override void doFinish(Database.BatchableContext bc) {
        try{
            if(isSuccess ){
                system.debug('SobjectCountMap----####--->'+SobjectCountMap.size()+' '+ SobjectCountMap);
                Datetime BatchEndTime = system.now();
                PrepareHashmap();
                SobjectCountMap.put('Int_Delivery_Control__c',      1);
              //SobjectCountMap.put('Int_File_Control__c',28);
                SobjectCountMap.put('Int_Facility__c',              0);
                SobjectCountMap.put('Int_Agreement_Non_IFRS__c',    0);  
                SobjectCountMap.put('Int_Agreement_Provision__c',   0); 
                SobjectCountMap.put('Int_Asset_Feature__c',         0);   
                SobjectCountMap.put('Int_Asset_Usage__c',           0);                     
                SobjectCountMap.put('Int_Facility_Feature__c',      0);    
                SobjectCountMap.put('Int_Facility_Party__c',        0);  
                SobjectCountMap.put('Int_Party_Feature__c',         0);   
                SobjectCountMap.put('Int_Risk_Costs_Movements__c',  0);   
                SobjectCountMap.put('Int_Agreement_Line_Feature__c',0);
                for(String obj: DataObjSet){
                    If(!SobjectCountMap.containskey(obj)){
                        SobjectCountMap.put(obj,0);
                    }
                }
                if(!SobjectCountMap.isEmpty()){
                    List<sobject> controlObjectsToInsert = new List<sobject>();
                    for(string ObjectName : SobjectCountMap.keySet()){
                        //Create file control objects here
                        controlObjectsToInsert.add(DMBIInterfaceRecordUtil.createFileControlObjects(ObjectName,SobjectCountMap.get(ObjectName),SobjectHashMap,BatchstartTime,BatchEndTime,IntCodeMapping));
                        //system.debug('**filename***' + controlObjectsToInsert.get(0).get('File_Name__c'));
                    }
                    //Create delivery control objects here
                    controlObjectsToInsert.add(DMBIInterfaceRecordUtil.createDeliveryControlObjects(BatchstartTime,IntCodeMapping));
                    if(!controlObjectsToInsert.isEmpty()){
                        Insert controlObjectsToInsert; 
                    }
                }
            }
        } catch(exception e){
            System.debug(LoggingLevel.ERROR, 'Exception while processing batch finish method: '+e.getMessage());
            System.debug(LoggingLevel.ERROR, 'Exception StackTrace: '+e.getStackTraceString()+ ' '+e.getLineNumber());
            
            insert new cllease__Batch_Process_Log__c(Name='DMBIInterfaceDAGJob finish() : ', cllease__Date__c = System.today(), 
            cllease__Message__c='Error is '+ ( e.getmessage().length()>255 ? e.getMessage().subString(0,255) : e.getMessage())
            +' in line number: '+ e.getlinenumber());
        }
    }
}