force-app/main/default/objects/Int_Agreement__c/Int_Agreement__c.object-meta.xml
<CustomObject>
    <description>Int Agreement</description>
    <label>Int Agreement</label>
    <nameField>
        <displayFormat>AGR-{0000000000}</displayFormat>
        <label>Agreement Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Agreement_Classification__c/Int_Agreement_Classification__c.object-meta.xml
<CustomObject>
    <description>Int Agreement Classification</description>
    <label>Int Agreement Classification</label>
    <nameField>
        <displayFormat>ACI-{0000000000}</displayFormat>
        <label>Agreement Classification Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Agreements Classification</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Agreement_Classification__c/fields/Committed__c.field-meta.xml
<CustomField>
    <fullName>Committed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Committed</description>
    <label>Committed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Int_Agreement_Exposure__c/Int_Agreement_Exposure__c.object-meta.xml
<CustomObject>
    <description>Int Agreement Exposure</description>
    <label>Int Agreement Exposure</label>
    <nameField>
        <displayFormat>AGE-{0000000000}</displayFormat>
        <label>Agreement Exposure Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Agreements Exposure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Agreement_Line_Feature__c/Int_Agreement_Line_Feature__c.object-meta.xml
<CustomObject>
    <description>Int Agreement Line Feature</description>
    <label>Int Agreement Line Feature</label>
    <nameField>
        <displayFormat>AFI-{0000000000}</displayFormat>
        <label>Agreement Feature Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Agreement Line Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Agreement_Party__c/Int_Agreement_Party__c.object-meta.xml
<CustomObject>
    <description>Int Agreement Party</description>
    <label>Int Agreement Party</label>
    <nameField>
        <displayFormat>API-{0000000000}</displayFormat>
        <label>Agreement Party Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Agreements Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Asset__c/Int_Asset__c.object-meta.xml
<CustomObject>
    <description>Int Asset</description>
    <label>Int Asset</label>
    <nameField>
        <displayFormat>AST-{0000000000}</displayFormat>
        <label>Asset Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Delivery_Control__c/Int_Delivery_Control__c.object-meta.xml
<CustomObject>
    <description>Int Delivery Control</description>
    <label>Int Delivery Control</label>
    <nameField>
        <displayFormat>DEL-{0000000000}</displayFormat>
        <label>Delivery Control Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Delivery Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_File_Control__c/Int_File_Control__c.object-meta.xml
<CustomObject>
    <description>Int File Control</description>
    <label>Int File Control</label>
    <nameField>
        <displayFormat>FCI-{0000000000}</displayFormat>
        <label>File Control Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Files Control</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Party__c/Int_Party__c.object-meta.xml
<CustomObject>
    <description>Int Party</description>
    <label>Int Party</label>
    <nameField>
        <displayFormat>PAR-{0000000000}</displayFormat>
        <label>Party Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Party_Feature__c/Int_Party_Feature__c.object-meta.xml
<CustomObject>
    <description>Int Party Feature</description>
    <label>Int Party Feature</label>
    <nameField>
        <displayFormat>PFI-{0000000000}</displayFormat>
        <label>Party Feature Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Party Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DMBIDataCleanUpDAGJobTest.cls
@isTest
public with sharing class DMBIDataCleanUpDAGJobTest {
	
	@isTest
	public static void validateCleanUpJob(){
        int_agreement__c agr = DMBIInterfaceJobDataTestFactory.createagreement();
        agr.Committed__c = true;
        update agr;

        // Creating Interface Object Records through Test Factory
        int_file_control__c fc 				= DMBIInterfaceJobDataTestFactory.createFilecontrol();
        Int_Asset__c asset 					= DMBIInterfaceJobDataTestFactory.createAsset();
        int_party__c party 					= DMBIInterfaceJobDataTestFactory.createEParty();
        int_delivery_control__c dc 			= DMBIInterfaceJobDataTestFactory.createDeliverycontrol();
        int_party_feature__c pf 			= DMBIInterfaceJobDataTestFactory.createPartyFeature(agr); 
        Int_Agreement_line_Feature__c ial 	= DMBIInterfaceJobDataTestFactory.createAgrlinefeature(agr);
        Int_Agreement_Party__c iap 			= DMBIInterfaceJobDataTestFactory.createAgrParty(agr);
        Int_Agreement_Exposure__c ae 		= DMBIInterfaceJobDataTestFactory.createAgrExposure(agr);
        Int_Agreement_Classification__c ac 	= DMBIInterfaceJobDataTestFactory.createAgrClassification(agr);
       
   		List<String> ObjectSet = new List<string>{
   					'Int_Agreement_Classification__c',
   					'Int_Agreement_Exposure__c',
   					'Int_Agreement_Party__c',
   					'Int_Agreement_line_Feature__c',
   					'int_party_feature__c',
   					'int_party__c',
   					'Int_Asset__c',
   					'Int_file_control__c',
   					'Int_Delivery_control__c',
   					'Int_Agreement__c'};
        for(string ObjectName : ObjectSet){
            Database.executeBatch(new DMBIDataCleanUpDAGJob(ObjectName), 1000);
         }
    }

    @isTest
	public static void validateScheduleJob(){
        int_agreement__c agr = DMBIInterfaceJobDataTestFactory.createagreement();
        agr.Committed__c = true;
        update agr;

        // Creating Interface Object Records through Test Factory
        int_file_control__c fc 				= DMBIInterfaceJobDataTestFactory.createFilecontrol();
        Int_Asset__c asset 					= DMBIInterfaceJobDataTestFactory.createAsset();
        int_party__c party 					= DMBIInterfaceJobDataTestFactory.createEParty();
        int_delivery_control__c dc 			= DMBIInterfaceJobDataTestFactory.createDeliverycontrol();
        int_party_feature__c pf 			= DMBIInterfaceJobDataTestFactory.createPartyFeature(agr); 
        Int_Agreement_line_Feature__c ial 	= DMBIInterfaceJobDataTestFactory.createAgrlinefeature(agr);
        Int_Agreement_Party__c iap 			= DMBIInterfaceJobDataTestFactory.createAgrParty(agr);
        Int_Agreement_Exposure__c ae 		= DMBIInterfaceJobDataTestFactory.createAgrExposure(agr);
        Int_Agreement_Classification__c ac 	= DMBIInterfaceJobDataTestFactory.createAgrClassification(agr);
       
   		// Running the Scheduled job
   		DMBIDataCleanUpScheduleJob scheduler = new DMBIDataCleanUpScheduleJob();
   		scheduler.execute(null);
    }

    @isTest
    public static void ValidateDMBIInterfaceJob(){
        list<cllease__Lease_Account__c> LeaseContactList = new list<cllease__Lease_Account__c>();
        LeaseContactList.add(TestHelper.createContract());
        DMBIInterfaceDAGJob DIJ = new DMBIInterfaceDAGJob();
        DataBase.executeBatch(DIJ, 50);
    }

}