force-app/main/default/objects/Int_Agreement__c/Int_Agreement__c.object-meta.xml
<CustomObject>
    <description>Int Agreement</description>
    <label>Int Agreement</label>
    <nameField>
        <displayFormat>AGR-{0000000000}</displayFormat>
        <label>Agreement Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Agreement_Classification__c/Int_Agreement_Classification__c.object-meta.xml
<CustomObject>
    <description>Int Agreement Classification</description>
    <label>Int Agreement Classification</label>
    <nameField>
        <displayFormat>ACI-{0000000000}</displayFormat>
        <label>Agreement Classification Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Agreements Classification</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Agreement_Classification__c/fields/Committed__c.field-meta.xml
<CustomField>
    <fullName>Committed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Committed</description>
    <label>Committed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Int_Agreement_Exposure__c/Int_Agreement_Exposure__c.object-meta.xml
<CustomObject>
    <description>Int Agreement Exposure</description>
    <label>Int Agreement Exposure</label>
    <nameField>
        <displayFormat>AGE-{0000000000}</displayFormat>
        <label>Agreement Exposure Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Agreements Exposure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Agreement_Line_Feature__c/Int_Agreement_Line_Feature__c.object-meta.xml
<CustomObject>
    <description>Int Agreement Line Feature</description>
    <label>Int Agreement Line Feature</label>
    <nameField>
        <displayFormat>AFI-{0000000000}</displayFormat>
        <label>Agreement Feature Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Agreement Line Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Agreement_Party__c/Int_Agreement_Party__c.object-meta.xml
<CustomObject>
    <description>Int Agreement Party</description>
    <label>Int Agreement Party</label>
    <nameField>
        <displayFormat>API-{0000000000}</displayFormat>
        <label>Agreement Party Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Agreements Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Asset__c/Int_Asset__c.object-meta.xml
<CustomObject>
    <description>Int Asset</description>
    <label>Int Asset</label>
    <nameField>
        <displayFormat>AST-{0000000000}</displayFormat>
        <label>Asset Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Delivery_Control__c/Int_Delivery_Control__c.object-meta.xml
<CustomObject>
    <description>Int Delivery Control</description>
    <label>Int Delivery Control</label>
    <nameField>
        <displayFormat>DEL-{0000000000}</displayFormat>
        <label>Delivery Control Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Delivery Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_File_Control__c/Int_File_Control__c.object-meta.xml
<CustomObject>
    <description>Int File Control</description>
    <label>Int File Control</label>
    <nameField>
        <displayFormat>FCI-{0000000000}</displayFormat>
        <label>File Control Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Files Control</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Party__c/Int_Party__c.object-meta.xml
<CustomObject>
    <description>Int Party</description>
    <label>Int Party</label>
    <nameField>
        <displayFormat>PAR-{0000000000}</displayFormat>
        <label>Party Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Party_Feature__c/Int_Party_Feature__c.object-meta.xml
<CustomObject>
    <description>Int Party Feature</description>
    <label>Int Party Feature</label>
    <nameField>
        <displayFormat>PFI-{0000000000}</displayFormat>
        <label>Party Feature Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Party Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DMBIDataCleanupJob_Test.cls
@isTest public class DMBIDataCleanupJob_Test {
    public static Id fcid;
    public static Id agrid;
    
   //Create test data and test Delete job.
    @testSetup static void creatTestData(){  
        //Create Agreement record      
        int_agreement__c agr = DMBIInterfaceJobDataFactoryTestUtil.createagreement();
        agrId = agr.id;
        agr.Committed__c = true;
        update agr;
        System.Assert((agr.ID != Null) && (agr.Committed__c = true));        
        
        //Create Asset record.
        Int_Asset__c asset = DMBIInterfaceJobDataFactoryTestUtil.createAsset();
        System.Assert(asset.ID != Null);
        
        //Create Party record.
        int_party__c party = DMBIInterfaceJobDataFactoryTestUtil.createEParty();
        System.Assert(party.ID != Null);
        
        //Create Delivery control record
        int_delivery_control__c dc = DMBIInterfaceJobDataFactoryTestUtil.createDeliverycontrol();
        System.Assert(dc.ID != Null);
        
        //Create Party feature record.
        int_party_feature__c pf = DMBIInterfaceJobDataFactoryTestUtil.createPartyFeature(agr); 
        System.Assert(pf.ID != Null);
        
        //Create agreement line feature record
        Int_Agreement_line_Feature__c ial = DMBIInterfaceJobDataFactoryTestUtil.createAgrlinefeature(agr);
        System.Assert(ial.ID != Null);
        
        //Create agreement party record.
        Int_Agreement_Party__c iap = DMBIInterfaceJobDataFactoryTestUtil.createAgrParty(agr);
        System.Assert(iap.ID != Null);
        
        //Create agreement exposure record
        Int_Agreement_Exposure__c ae = DMBIInterfaceJobDataFactoryTestUtil.createAgrExposure(agr);
        System.Assert(ae.ID != Null);
        
        //Create agreement classification record
        Int_Agreement_Classification__c ac =DMBIInterfaceJobDataFactoryTestUtil.createAgrClassification(agr);
        System.Assert(ac.ID != Null);
        
        //Create File control record.
        int_file_control__c fc = DMBIInterfaceJobDataFactoryTestUtil.createFilecontrol();
        fcid = fc.Id;
        update fc;
        System.Assert(fc.ID != Null);        
    } 
    
    //Delete file control record created above.   
    @isTest public static void deletefilecontrolData(){    
         Test.startTest();
        Database.executeBatch(new DMBIDataCleanUpJob('int_file_control__c'),10);
        Test.stopTest();
        List<int_file_control__c> deletedfc = [Select Id From int_file_control__c where Id = :fcId];
        System.Assert(deletedfc.size()==0);                           
     }
     
    //Delete agreement record created above.   
    @isTest public static void deleteAgreementData(){    
         Test.startTest();
        Database.executeBatch(new DMBIDataCleanUpJob('int_agreement__c'),10);
        Test.stopTest();
        List<int_agreement__c> deletedagr = [Select Id From int_agreement__c where Id = :agrId];
        System.Assert(deletedagr.size()==0);                           
     }
}