force-app/main/default/objects/Int_OLMN_Accounting_Entry__c/Int_OLMN_Accounting_Entry__c.object-meta.xml
<CustomObject>
    <description>This contains interface account entry subledger information headed to newco oracle</description>
    <label>Int OLMN Accounting Entry</label>
    <nameField>
        <displayFormat>AE-{00000000}</displayFormat>
        <label>Int OLMN Accounting Entrie Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int OLMN Accounting Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_OLMN_AP__c/Int_OLMN_AP__c.object-meta.xml
<CustomObject>
    <description>This contains interface ap information headed to newco oracle

MD50 - Interface GLBLxxxx – AP Payments to NEWCO</description>
    <label>Int OLMN AP</label>
    <nameField>
        <displayFormat>AP-{00000000}</displayFormat>
        <label>Int OLMN AP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int OLMN AP</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_OLMN_AP__c/fields/Committed__c.field-meta.xml
<CustomField>
    <fullName>Committed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Committed?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_GL__c/Int_OLMN_GL__c.object-meta.xml
<CustomObject>
    <description>This contains the data for the gl interface</description>
    <label>Int OLMN GL</label>
    <nameField>
        <displayFormat>GL-{00000000}</displayFormat>
        <label>General Ledger Out Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int OLMN GL</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_OLMN_GL__c/fields/Committed__c.field-meta.xml
<CustomField>
    <fullName>Committed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This indicates if the data has been committed in the destination system.</description>
    <label>Committed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Int_OLMN_Net_Investment__c/Int_OLMN_Net_Investment__c.object-meta.xml
<CustomObject>
    <description>This contains interface net investment subledger information headed to newco oracle</description>
    <label>Int OLMN Net Investment</label>
    <nameField>
        <displayFormat>NI-{00000000}</displayFormat>
        <label>Int OLMN Net Investment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int OLMN Net Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_PX_Billing__c/Int_PX_Billing__c.object-meta.xml
<CustomObject>
    <description>This contains PNC billing transactions headed to PNC</description>
    <label>Int PX Billing</label>
    <nameField>
        <displayFormat>B-{00000000}</displayFormat>
        <label>Int PX  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int PX Billing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/InterfaceTablesUnfinishedTxnsCheck.cls
/**
 * Owner: Cloud Lending Solutions
 * Description: Following Class helps in checking unfinished Transactions in Interface tables
 * List of jobs
 * 		1. GL Consolidation Job 
 *				Class: GLConsolidatedEntriesBatch.cls
 *				Object: Int_OLMN_GL__c
 *		2. GL SubLedgers Job
 *				Class: GLSubledgerEntriesBatch.cls
 *				Object: Int_OLMN_Accounting_Entry__c
 *		3. AP Integration
 *				Class: PopulateAPinterfaceDealerfunding.cls
 *				Object: Int_OLMN_AP__c
 *		4. PNC Integration 
 *				Class: PNCFileCreationJob.cls
 *				Object: Int_PX_Billing__c
 * 
 **/
public with sharing class InterfaceTablesUnfinishedTxnsCheck {
	
	// return true if any remaining unfinished transactions in interface table
	// else false if there are no unfinished transactions in interface table
	public static Boolean checkUnfinishedTxnsForGLConsolidations() {
		List<Int_OLMN_GL__c> unfinishedTxns = [SELECT Id
													FROM Int_OLMN_GL__c
													WHERE Committed__c = false];
		if(unfinishedTxns.size() > 0) {
			return true;
		} else {
			return false;
		}
	}

	// return true if any remaining unfinished transactions in interface table
	// else false if there are no unfinished transactions in interface table
	public static Boolean checkUnfinishedTxnsForGLSubLedgers() {
		List<Int_OLMN_Accounting_Entry__c> unfinishedTxns 
												= [SELECT Id
													FROM Int_OLMN_Accounting_Entry__c
													WHERE Committed__c = false];
		if(unfinishedTxns.size() > 0) {
			return true; 
		} else {
			return false;
		}
	}

	// return true if any remaining unfinished transactions in interface table
	// else false if there are no unfinished transactions in interface table
	public static Boolean checkUnfinishedTxnsForAPIntegration() {
		List<Int_OLMN_AP__c> unfinishedTxns 	= [SELECT Id
													FROM Int_OLMN_AP__c
													WHERE Committed__c = false];
		if(unfinishedTxns.size() > 0) {
			return true; 
		} else {
			return false;
		}
	}

	// return true if any remaining unfinished transactions in interface table
	// else false if there are no unfinished transactions in interface table
	public static Boolean checkUnfinishedTxnsForPNCIntegration() {
		List<Int_PX_Billing__c> unfinishedTxns 	= [SELECT Id
													FROM Int_PX_Billing__c
													WHERE Committed__c = false];
        System.debug('unFinishedTxns.size = ' + unfinishedTxns.size());
		if(unfinishedTxns.size() > 0) {
			return true; //ahr
		} else {
			return false; //ahr
		}
	}

	// return true if any remaining unfinished transactions in interface table
	// else false if there are no unfinished transactions in interface table
	public static Boolean checkUnfinishedTxnsForNetInvestmentReport() {
		List<Int_OLMN_Net_Investment__c> unfinishedTxns = [SELECT Id
													FROM Int_OLMN_Net_Investment__c
													WHERE Committed__c = false];
		if(unfinishedTxns.size() > 0) {
			return true;
		} else {
			return false;
		}
	}
}